# C: *Methods* example {-}

```{block2, type="rmdwarning", echo=T}
**WARNING**: This document will be uploaded to Turnitin. It will also have been read by your classmates. Therefore, it is a very bad idea to copy this to modify to use in your own results section. Doing so would be a form of plagiarism. 
```

The survey design and data for the example *Method* section below is adapted from a classroom project by Fettig, López Fuentes, and Villarreal [-@FettigLopezfuentesVillarreal2019]:^[Permission to use their data was given each author separately in late September, 2019, via a series of email exchanges.] 

> **Method**
>
>**Participants**
>
>There were a total of 37 participants who completed the survey. Twenty-three of them were women (62.2%), and the remainder were men (*n* = 14, 37.8%). The ages (in years) ranged from 18 to 22 (*M* = 19.1, *SD* = 0.95), with the men being slightly older and more varied in age (*M* = 19.4, *SD* = 1.09) than the women (*M* = 19.0, *SD* = 0.825). The mean, the median, and the mode of age were all equal at 19.
>
>The participants were recruited via convenience sampling through two *GroupMe* accounts shared by students from two large classes in Psychology at Texas A&M from the previous year.
>
>
>**Materials**
>
>The survey consisted of eleven questions overall. Two of the variables measured participant demographics: *Sex* (*male* vs. *female*); and *Age* (in years). Two other questions had to do with administration (covered in *Procedures* below). The remaining seven variables had directly to do with the research questions at hand. These are covered next in the order in which they appeared in the survey to the participants.

> 	*Outcome variables*. There were three outcome variables that were designed to be averaged into a single composite, outcome variable: *Sleep Quality*. The first, *Sleep Satisfaction*, was worded as follows: “How satisfied are you with the amount of sleep you get each night?” Responses were measured on a Likert scale from 1 to 5, with 1 corresponding to “Not at all satisfied,” and 5 corresponding to “Very satisfied.” The second variable *Restedness*, was worded in the survey as follows: “On a scale of 1 to 5, how rested do you feel on average?” This question used the same scale, with 1 corresponding to “Not at all rested,” and 5 corresponding to “Very rested.” Finally, the third outcome variable, *Typical Hours Slept*, was simply the number of hours that the participant estimated they slept per night. This number was entered directly by the participant.

>  *Predictor variables*. There were four predictor variables. The first two were nominal variables. One was a two-level nominal variable called *Extracurricular Activities*.The question that corresponded to the variable was as follows: “Are you a part of extra curricular activities? i.e., clubs, sports, greek life.” Participants could answer either "Yes" or "No." The other nominal variable was a three-level variable called *Employment Status* ("Are you employed?"). There were three options for the participant: "No," "Full-time," and "Part-time." The next two predictor variables were continuous. The first of these was *Academic Hours* (“How many academic hours are you currently taking?”). Participants entered the number of credit hours they were taking that semester. The second (and last of the four predictor variables) was *Workload Intensity*: “How do you rate the intensity of your overall workload, including academic, work-related, and extracurricular commitments?” This was measured on a 1-5 Likert scale with 1 corresponding to "Not intense at all," and 5 corresponding to "Very intense."
>
>
>**Design & Analysis**
>
>We were interested in how *Sleep Quality* (the composite, outcome variable) was predicted by whether students were involved in extracurricular activities, the degree to which they were employed, their current academic course load, and the intensity of their general workload (work, academic, and otherwise).
>
>The calculation of the composite variable, *Sleep Quality*, first required the conversion of the three, raw outcome variables into *z*-scores, and from there into a composite score. Thus, the following variables were converted to z-scores: *Sleep Satisfaction* (*M* = 3, *SD* = 1); *Restedness* (*M* = 2.92, *SD* = 1.12); and *Typical Hours Slept* (*M* = 6.45, *SD* = 1.12).
>
>After the standardization into *z*-scores, the three newly standardized scores were averaged into the single composite. An internal reliability analysis showed that item consistency was quite high (Cronbach’s Alpha = 0.86). An analysis at the Alpha-level change due to single-item dropping revealed that removing any of the items would result in a drop in Alpha. Therefore, all three variables were retained for the composite. The resulting composite, *Sleep Quality* (*M* = 0, *SD* = 0.883) ranged from a score of -2.39 to a maximum score of 1.73. This served as the single outcome variable in all subsequent analyses.
>
>
>**Procedures**
>
>The researchers simply sent the link to this survey out to potential respondents in the *GroupMe* list mentioned above under *Participants*. Upon receiving the survey, participants were informed about the nature of the study, that participation was optional, and that no personally identifying information would be recorded. At this point, there were given the opportunity to opt out of the study. 
>
>If they continued with the study, they were asked all the questions mentioned above in the same order as above. Importantly, the participants were not required to respond to any of the questions; they could leave any response blank if they so chose. Finally, at the end of the study, participants were given the option to exclude their data from analysis. None of the participants chose this option.
>
>After two weeks of soliciting responses, the final data set was selected for analysis.
