<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Categorical data analysis | A Lab Manual for PSYC 301: Elementary Statistics for Psychology</title>
  <meta name="description" content="This is a lab manual for PSYC 301: Elementary Statistics for Psychology. It is an open educational resource (OER), so there is no charge to students." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Categorical data analysis | A Lab Manual for PSYC 301: Elementary Statistics for Psychology" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://patrickabolger.github.io/ElemStatsLabManual/" />
  
  <meta property="og:description" content="This is a lab manual for PSYC 301: Elementary Statistics for Psychology. It is an open educational resource (OER), so there is no charge to students." />
  <meta name="github-repo" content="patrickabolger/ElemStatsLabManual" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Categorical data analysis | A Lab Manual for PSYC 301: Elementary Statistics for Psychology" />
  
  <meta name="twitter:description" content="This is a lab manual for PSYC 301: Elementary Statistics for Psychology. It is an open educational resource (OER), so there is no charge to students." />
  



<meta name="date" content="2021-05-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="DataVisualization.html"/>
<link rel="next" href="ComparingTwoMeans.html"/>
<script src="libs/header-attrs-2.8/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />



<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Lab Manual for PSYC 301: Elementary Statistics for Psychology</a></li>
<li><a href="./">Patrick Bolger, PhD.</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#goals"><i class="fa fa-check"></i><b>0.1</b> Goals</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#Resources"><i class="fa fa-check"></i><b>0.2</b> Resources</a>
<ul>
<li class="chapter" data-level="0.2.1" data-path="index.html"><a href="index.html#FixedResources"><i class="fa fa-check"></i><b>0.2.1</b> Fixed resources</a></li>
<li class="chapter" data-level="0.2.2" data-path="index.html"><a href="index.html#Software"><i class="fa fa-check"></i><b>0.2.2</b> Software</a></li>
</ul></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#RationaleForJamovi"><i class="fa fa-check"></i><b>0.3</b> Rationale for jamovi</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#OrganizationOfThisManual"><i class="fa fa-check"></i><b>0.4</b> Organization of this manual</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#MainOutcomeOfClass"><i class="fa fa-check"></i><b>0.5</b> Main outcome of class</a></li>
</ul></li>
<li class="part"><span><b>I Basics</b></span></li>
<li class="chapter" data-level="1" data-path="GettingUsedtoJamovi.html"><a href="GettingUsedtoJamovi.html"><i class="fa fa-check"></i><b>1</b> Getting used to jamovi</a>
<ul>
<li class="chapter" data-level="1.1" data-path="GettingUsedtoJamovi.html"><a href="GettingUsedtoJamovi.html#DownloadingAndInstallingJamovi"><i class="fa fa-check"></i><b>1.1</b> Downloading and installing</a></li>
<li class="chapter" data-level="1.2" data-path="GettingUsedtoJamovi.html"><a href="GettingUsedtoJamovi.html#NavigatingJamovi"><i class="fa fa-check"></i><b>1.2</b> Navigation</a></li>
<li class="chapter" data-level="1.3" data-path="GettingUsedtoJamovi.html"><a href="GettingUsedtoJamovi.html#OutsideHelpOnBasics"><i class="fa fa-check"></i><b>1.3</b> Outside help on basics</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="GettingUsedtoJamovi.html"><a href="GettingUsedtoJamovi.html#OutsideHelpOnOveralIntroduction"><i class="fa fa-check"></i><b>1.3.1</b> Overall introduction</a></li>
<li class="chapter" data-level="1.3.2" data-path="GettingUsedtoJamovi.html"><a href="GettingUsedtoJamovi.html#OutsideHelpOnDownloadingAndInstalling"><i class="fa fa-check"></i><b>1.3.2</b> Downloading and installing</a></li>
<li class="chapter" data-level="1.3.3" data-path="GettingUsedtoJamovi.html"><a href="GettingUsedtoJamovi.html#OutsideHelpOnNavigating"><i class="fa fa-check"></i><b>1.3.3</b> Navigating</a></li>
<li class="chapter" data-level="1.3.4" data-path="GettingUsedtoJamovi.html"><a href="GettingUsedtoJamovi.html#OutsideHelpOnModules"><i class="fa fa-check"></i><b>1.3.4</b> Modules</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="GettingUsedtoJamovi.html"><a href="GettingUsedtoJamovi.html#ConclusionOfBasics"><i class="fa fa-check"></i><b>1.4</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html"><i class="fa fa-check"></i><b>2</b> Basic data operations</a>
<ul>
<li class="chapter" data-level="2.1" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#Manualling"><i class="fa fa-check"></i><b>2.1</b> Entering data manually</a></li>
<li class="chapter" data-level="2.2" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#Opening"><i class="fa fa-check"></i><b>2.2</b> Opening data files</a></li>
<li class="chapter" data-level="2.3" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#Importing"><i class="fa fa-check"></i><b>2.3</b> Importing data</a></li>
<li class="chapter" data-level="2.4" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#Exporting"><i class="fa fa-check"></i><b>2.4</b> Exporting data</a></li>
<li class="chapter" data-level="2.5" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#ManipulatingData"><i class="fa fa-check"></i><b>2.5</b> Manipulating data</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#ComputingNewVariables"><i class="fa fa-check"></i><b>2.5.1</b> Computing new variables</a></li>
<li class="chapter" data-level="2.5.2" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#FilteringData"><i class="fa fa-check"></i><b>2.5.2</b> Filtering data</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#GeneralNoteUnderstandingTidyness"><i class="fa fa-check"></i><b>2.6</b> General note: Understanding <em>tidy</em>-ness</a></li>
<li class="chapter" data-level="2.7" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#OutsideHelpOnBasicDataOperations"><i class="fa fa-check"></i><b>2.7</b> Outside help on basic data preparation</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#OutsideHelpOnEnteringData"><i class="fa fa-check"></i><b>2.7.1</b> Entering and adjusting data</a></li>
<li class="chapter" data-level="2.7.2" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#OutsideHelpOnOpeningData"><i class="fa fa-check"></i><b>2.7.2</b> Opening data</a></li>
<li class="chapter" data-level="2.7.3" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#OutsideHelpOnImportingData"><i class="fa fa-check"></i><b>2.7.3</b> Importing data</a></li>
<li class="chapter" data-level="2.7.4" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#OutsideHelpOnRecodingVariables"><i class="fa fa-check"></i><b>2.7.4</b> Re-coding variables</a></li>
<li class="chapter" data-level="2.7.5" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#OutsideHelpOnGeneratingRandomData"><i class="fa fa-check"></i><b>2.7.5</b> Generating random data</a></li>
<li class="chapter" data-level="2.7.6" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#OutsideHelpOnTransormingVariables"><i class="fa fa-check"></i><b>2.7.6</b> Transforming variables</a></li>
<li class="chapter" data-level="2.7.7" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#OutsideHelpOnFilteringData"><i class="fa fa-check"></i><b>2.7.7</b> Filtering data</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#BasicDataPreprationPracticeExercises"><i class="fa fa-check"></i><b>2.8</b> Practice Exercises</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#PracManualing"><i class="fa fa-check"></i><b>2.8.1</b> Practice entering data</a></li>
<li class="chapter" data-level="2.8.2" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#PracticeExporting"><i class="fa fa-check"></i><b>2.8.2</b> Practice exporting</a></li>
<li class="chapter" data-level="2.8.3" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#PracticeImporting"><i class="fa fa-check"></i><b>2.8.3</b> Practice importing</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html"><i class="fa fa-check"></i><b>3</b> Descriptive statistics</a>
<ul>
<li class="chapter" data-level="3.1" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#OverviewOfDescriptiveStats"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#DescriptivesInJamovi"><i class="fa fa-check"></i><b>3.2</b> Descriptives in jamovi</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#SummarizingContinuousVariables"><i class="fa fa-check"></i><b>3.2.1</b> Summarizing continuous variables</a></li>
<li class="chapter" data-level="3.2.2" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#GroupedSummaries"><i class="fa fa-check"></i><b>3.2.2</b> Grouped summaries</a></li>
<li class="chapter" data-level="3.2.3" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#Frequencies"><i class="fa fa-check"></i><b>3.2.3</b> Frequencies</a></li>
<li class="chapter" data-level="3.2.4" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#reporting-data-summaries"><i class="fa fa-check"></i><b>3.2.4</b> Reporting data summaries</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#OutsideHelpOnDescriptives"><i class="fa fa-check"></i><b>3.3</b> Outside help on descriptives</a></li>
<li class="chapter" data-level="3.4" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#PracticeSummarizingAndReporting"><i class="fa fa-check"></i><b>3.4</b> Practice summarizing and reporting</a></li>
<li class="chapter" data-level="3.5" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#GlossaryOfDescriptives"><i class="fa fa-check"></i><b>3.5</b> Glossary of descriptives</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#CentralTendency"><i class="fa fa-check"></i><b>3.5.1</b> Central tendency</a></li>
<li class="chapter" data-level="3.5.2" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#Dispersion"><i class="fa fa-check"></i><b>3.5.2</b> Dispersion</a></li>
<li class="chapter" data-level="3.5.3" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#diagnostics"><i class="fa fa-check"></i><b>3.5.3</b> Diagnostics</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="DataVisualization.html"><a href="DataVisualization.html"><i class="fa fa-check"></i><b>4</b> Data visualizations</a>
<ul>
<li class="chapter" data-level="4.1" data-path="DataVisualization.html"><a href="DataVisualization.html#Histograms"><i class="fa fa-check"></i><b>4.1</b> Histograms</a></li>
<li class="chapter" data-level="4.2" data-path="DataVisualization.html"><a href="DataVisualization.html#Boxplots"><i class="fa fa-check"></i><b>4.2</b> Boxplots</a></li>
<li class="chapter" data-level="4.3" data-path="DataVisualization.html"><a href="DataVisualization.html#ViolinPlots"><i class="fa fa-check"></i><b>4.3</b> Violin plots</a></li>
<li class="chapter" data-level="4.4" data-path="DataVisualization.html"><a href="DataVisualization.html#DotPlots"><i class="fa fa-check"></i><b>4.4</b> Dot plots</a></li>
<li class="chapter" data-level="4.5" data-path="DataVisualization.html"><a href="DataVisualization.html#Barplots"><i class="fa fa-check"></i><b>4.5</b> Bar plots</a></li>
<li class="chapter" data-level="4.6" data-path="DataVisualization.html"><a href="DataVisualization.html#QQPlots"><i class="fa fa-check"></i><b>4.6</b> Q-Q plots</a></li>
<li class="chapter" data-level="4.7" data-path="DataVisualization.html"><a href="DataVisualization.html#outside-help-on-visualization"><i class="fa fa-check"></i><b>4.7</b> Outside help on visualization</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="DataVisualization.html"><a href="DataVisualization.html#OutsideHelpOnHistograms"><i class="fa fa-check"></i><b>4.7.1</b> Histograms</a></li>
<li class="chapter" data-level="4.7.2" data-path="DataVisualization.html"><a href="DataVisualization.html#OutsideHelpOnBoxPlots"><i class="fa fa-check"></i><b>4.7.2</b> Boxplots</a></li>
<li class="chapter" data-level="4.7.3" data-path="DataVisualization.html"><a href="DataVisualization.html#OutsideHelpOnViolinPlots"><i class="fa fa-check"></i><b>4.7.3</b> Violin plots</a></li>
<li class="chapter" data-level="4.7.4" data-path="DataVisualization.html"><a href="DataVisualization.html#OutsideHelpOnDotPlots"><i class="fa fa-check"></i><b>4.7.4</b> Dot plots</a></li>
<li class="chapter" data-level="4.7.5" data-path="DataVisualization.html"><a href="DataVisualization.html#bar-plots-outsidehelponbarplots"><i class="fa fa-check"></i><b>4.7.5</b> Bar plots (#OutsideHelpOnBarPlots)</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Inferential statistics</b></span></li>
<li class="chapter" data-level="5" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html"><i class="fa fa-check"></i><b>5</b> Categorical data analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html#ChiSquareGoodnessOfFit"><i class="fa fa-check"></i><b>5.1</b> Chi-square goodness-of-fit test</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html#ChiSquareGoodnessOfFitBasicCards"><i class="fa fa-check"></i><b>5.1.1</b> Basic: The Cards data</a></li>
<li class="chapter" data-level="5.1.2" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html#ChiSquareGoodnessOfFitAdvancedUCBAdmit"><i class="fa fa-check"></i><b>5.1.2</b> Advanced: Student admissions at UC Berkeley</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html#ChiSquareTestOfIndependence"><i class="fa fa-check"></i><b>5.2</b> Chi-square test of independence</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html#ChiSquareTestOfIndependenceChapek9"><i class="fa fa-check"></i><b>5.2.1</b> Basic: The <em>Chapek 9</em> data</a></li>
<li class="chapter" data-level="5.2.2" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html#NarcissisticPersonalityInventory"><i class="fa fa-check"></i><b>5.2.2</b> Advanced: The Narcissistic Personality Inventory</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html#OutsideHelpOnChisquare"><i class="fa fa-check"></i><b>5.3</b> Outside help on chi-square</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html#OutsideHelpOnGoodnessOfFit"><i class="fa fa-check"></i><b>5.3.1</b> Goodness-of-fit test</a></li>
<li class="chapter" data-level="5.3.2" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html#OutsideHelpOnChisquareTestOfIndependence"><i class="fa fa-check"></i><b>5.3.2</b> Chi-square test of independence</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html"><i class="fa fa-check"></i><b>6</b> Comparing two means</a>
<ul>
<li class="chapter" data-level="6.1" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#DoingIndSamplesTTest"><i class="fa fa-check"></i><b>6.1</b> The independent-samples <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#IndSamplesDrHarpo"><i class="fa fa-check"></i><b>6.1.1</b> Basic: Dr. Harpo’s statistics class</a></li>
<li class="chapter" data-level="6.1.2" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#IndSamplesConspiracyData"><i class="fa fa-check"></i><b>6.1.2</b> Advanced 1: The conspiracy data</a></li>
<li class="chapter" data-level="6.1.3" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#IndSamplesSpokeWrit"><i class="fa fa-check"></i><b>6.1.3</b> Advanced 2: Spoken vs. written pitches</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#DoingPairedSamplesTTest"><i class="fa fa-check"></i><b>6.2</b> The paired-samples <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#PairedSamplesChicoBasicData"><i class="fa fa-check"></i><b>6.2.1</b> Basic: The <em>Chico</em> data</a></li>
<li class="chapter" data-level="6.2.2" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#PairedSamplesChicoAdvancedData"><i class="fa fa-check"></i><b>6.2.2</b> Advanced 1: Randomly generated <em>Chico</em> data</a></li>
<li class="chapter" data-level="6.2.3" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#PairedSamplesSingingParents"><i class="fa fa-check"></i><b>6.2.3</b> Advanced 2: Singing parents</a></li>
<li class="chapter" data-level="6.2.4" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#PairedSamplesSingingParentsStudentTask"><i class="fa fa-check"></i><b>6.2.4</b> Your tasks</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#OutsideHelpOnComparingTwoMeans"><i class="fa fa-check"></i><b>6.3</b> Outside help on <em>t</em>-tests</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#OutsideHelpOnIndependentSamplesT"><i class="fa fa-check"></i><b>6.3.1</b> Independent samples <em>t</em>-test</a></li>
<li class="chapter" data-level="6.3.2" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#OutsideHelpOnPairedSamplesT"><i class="fa fa-check"></i><b>6.3.2</b> Paired samples <em>t</em>-test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="CorrAndLinearReg.html"><a href="CorrAndLinearReg.html"><i class="fa fa-check"></i><b>7</b> Correlation and linear regression</a>
<ul>
<li class="chapter" data-level="7.1" data-path="CorrAndLinearReg.html"><a href="CorrAndLinearReg.html#Correlations"><i class="fa fa-check"></i><b>7.1</b> Correlations</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="CorrAndLinearReg.html"><a href="CorrAndLinearReg.html#BasicCorrelationParenthood"><i class="fa fa-check"></i><b>7.1.1</b> Basic: Parenthood data</a></li>
<li class="chapter" data-level="7.1.2" data-path="CorrAndLinearReg.html"><a href="CorrAndLinearReg.html#AdvancedCorrelationSPRING2020"><i class="fa fa-check"></i><b>7.1.2</b> Advanced</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="CorrAndLinearReg.html"><a href="CorrAndLinearReg.html#LinearRegression"><i class="fa fa-check"></i><b>7.2</b> Linear regression</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="CorrAndLinearReg.html"><a href="CorrAndLinearReg.html#BasicRegressionParenthood"><i class="fa fa-check"></i><b>7.2.1</b> Basic: Parenthood data (again)</a></li>
<li class="chapter" data-level="7.2.2" data-path="CorrAndLinearReg.html"><a href="CorrAndLinearReg.html#AdvancedRegressionSPRING2020"><i class="fa fa-check"></i><b>7.2.2</b> Advanced:</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="CorrAndLinearReg.html"><a href="CorrAndLinearReg.html#MultipleLinearRegression"><i class="fa fa-check"></i><b>7.3</b> Multiple linear regression</a></li>
<li class="chapter" data-level="7.4" data-path="CorrAndLinearReg.html"><a href="CorrAndLinearReg.html#OutsideHelpOnCorrelation"><i class="fa fa-check"></i><b>7.4</b> Outside help on correlation</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ComparingSeveralMeans.html"><a href="ComparingSeveralMeans.html"><i class="fa fa-check"></i><b>8</b> Comparing several means</a>
<ul>
<li class="chapter" data-level="8.1" data-path="ComparingSeveralMeans.html"><a href="ComparingSeveralMeans.html#OnewayAnova"><i class="fa fa-check"></i><b>8.1</b> The One-Way ANOVA</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="ComparingSeveralMeans.html"><a href="ComparingSeveralMeans.html#OnewayAnovaClinicalTrialData"><i class="fa fa-check"></i><b>8.1.1</b> Basic: Clinical Trial data</a></li>
<li class="chapter" data-level="8.1.2" data-path="ComparingSeveralMeans.html"><a href="ComparingSeveralMeans.html#advanced"><i class="fa fa-check"></i><b>8.1.2</b> Advanced</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="ComparingSeveralMeans.html"><a href="ComparingSeveralMeans.html#repeated-measures-one-way-anova"><i class="fa fa-check"></i><b>8.2</b> Repeated-measures One-Way ANOVA</a></li>
<li class="chapter" data-level="8.3" data-path="ComparingSeveralMeans.html"><a href="ComparingSeveralMeans.html#outside-help-on-one-way-anova"><i class="fa fa-check"></i><b>8.3</b> Outside help on One-Way ANOVA</a></li>
<li class="chapter" data-level="8.4" data-path="ComparingSeveralMeans.html"><a href="ComparingSeveralMeans.html#PracticingOnewayAnova"><i class="fa fa-check"></i><b>8.4</b> Extra practice One-Way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="FactorialAnova.html"><a href="FactorialAnova.html"><i class="fa fa-check"></i><b>9</b> Factorial ANOVA</a>
<ul>
<li class="chapter" data-level="9.1" data-path="FactorialAnova.html"><a href="FactorialAnova.html#BasicFactorialAnovaJoyzepam"><i class="fa fa-check"></i><b>9.1</b> Basic: joyzepam data</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="FactorialAnova.html"><a href="FactorialAnova.html#BasicFactorialAnovaJoyzepamObtainingTheData"><i class="fa fa-check"></i><b>9.1.1</b> Obtaining the data</a></li>
<li class="chapter" data-level="9.1.2" data-path="FactorialAnova.html"><a href="FactorialAnova.html#BasicFactorialAnovaJoyzepamImplementing"><i class="fa fa-check"></i><b>9.1.2</b> Implementing the procedure</a></li>
<li class="chapter" data-level="9.1.3" data-path="FactorialAnova.html"><a href="FactorialAnova.html#BasicFactorialAnovaJoyzepamInterpreting"><i class="fa fa-check"></i><b>9.1.3</b> Interpreting the output</a></li>
<li class="chapter" data-level="9.1.4" data-path="FactorialAnova.html"><a href="FactorialAnova.html#BasicFactorialAnovaJoyzepamReporting"><i class="fa fa-check"></i><b>9.1.4</b> Reporting the output</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="FactorialAnova.html"><a href="FactorialAnova.html#AdvancedFactorialAnova_NAME"><i class="fa fa-check"></i><b>9.2</b> Advanced: advanced data NAME</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="FactorialAnova.html"><a href="FactorialAnova.html#AdvancedFactorialAnova_NAMEObtainingTheData"><i class="fa fa-check"></i><b>9.2.1</b> Obtaining the data</a></li>
<li class="chapter" data-level="9.2.2" data-path="FactorialAnova.html"><a href="FactorialAnova.html#AdvancedFactorialAnova_NAMEImplementing"><i class="fa fa-check"></i><b>9.2.2</b> Implementing the procedure</a></li>
<li class="chapter" data-level="9.2.3" data-path="FactorialAnova.html"><a href="FactorialAnova.html#AdvancedFactorialAnova_NAMEInterpreting"><i class="fa fa-check"></i><b>9.2.3</b> Interpreting the output</a></li>
<li class="chapter" data-level="9.2.4" data-path="FactorialAnova.html"><a href="FactorialAnova.html#AdvancedFactorialAnova_NAMEReporting"><i class="fa fa-check"></i><b>9.2.4</b> Reporting the output</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="FactorialAnova.html"><a href="FactorialAnova.html#ConclusionOfFactorialAnova"><i class="fa fa-check"></i><b>9.3</b> Conclusion</a></li>
<li class="chapter" data-level="9.4" data-path="FactorialAnova.html"><a href="FactorialAnova.html#OutsideHelpOnFactorialAnova"><i class="fa fa-check"></i><b>9.4</b> Outside help on factorial ANOVA</a></li>
<li class="chapter" data-level="9.5" data-path="FactorialAnova.html"><a href="FactorialAnova.html#PracticingFactorialAnova"><i class="fa fa-check"></i><b>9.5</b> Extra practice on factorial ANOVA</a></li>
</ul></li>
<li class="part"><span><b>III Research projects</b></span></li>
<li class="chapter" data-level="10" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html"><i class="fa fa-check"></i><b>10</b> Survey Design and Data Collection</a>
<ul>
<li class="chapter" data-level="10.1" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#ResearchProjectsOverview"><i class="fa fa-check"></i><b>10.1</b> Unit Overview</a></li>
<li class="chapter" data-level="10.2" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#SurveyDesignAndDataCollectionChapterOverview"><i class="fa fa-check"></i><b>10.2</b> Chapter Overview</a></li>
<li class="chapter" data-level="10.3" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#WhatIsScience"><i class="fa fa-check"></i><b>10.3</b> What is <em>Science</em>?</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#WhatIsMeasurement"><i class="fa fa-check"></i><b>10.3.1</b> What is <em>measurement</em>?</a></li>
<li class="chapter" data-level="10.3.2" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#WhatAreConstructs"><i class="fa fa-check"></i><b>10.3.2</b> What are <em>constructs</em>?</a></li>
<li class="chapter" data-level="10.3.3" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#WhatIsOperationalization"><i class="fa fa-check"></i><b>10.3.3</b> What is <em>operationalization</em>?</a></li>
<li class="chapter" data-level="10.3.4" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#WhatAreVariables"><i class="fa fa-check"></i><b>10.3.4</b> What are <em>variables</em>?</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#DesigningTheSurvey"><i class="fa fa-check"></i><b>10.4</b> Designing the survey</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#VariablesInYourStudy"><i class="fa fa-check"></i><b>10.4.1</b> Variables in your study</a></li>
<li class="chapter" data-level="10.4.2" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#MoreInformationOnSurveyQuestions"><i class="fa fa-check"></i><b>10.4.2</b> More information on survey questions</a></li>
<li class="chapter" data-level="10.4.3" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#SummaryOfSurveyDesignAssignment"><i class="fa fa-check"></i><b>10.4.3</b> Summary of <em>Survey Design</em> assignment</a></li>
<li class="chapter" data-level="10.4.4" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#OutsideHelpOnSurveys"><i class="fa fa-check"></i><b>10.4.4</b> Outside help on surveys</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#CollectingTheData"><i class="fa fa-check"></i><b>10.5</b> Collecting the Data</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html"><i class="fa fa-check"></i><b>11</b> Data Preparation and Analyses</a>
<ul>
<li class="chapter" data-level="11.1" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#DataPreparationAndAnalysesChapterOverview"><i class="fa fa-check"></i><b>11.1</b> Chapter overview</a></li>
<li class="chapter" data-level="11.2" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataExportingDataFromGoogleForms"><i class="fa fa-check"></i><b>11.2</b> Exporting data from Google Forms</a></li>
<li class="chapter" data-level="11.3" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataImportingTheData"><i class="fa fa-check"></i><b>11.3</b> Importing the data into jamovi</a></li>
<li class="chapter" data-level="11.4" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataCleaningUpTheData"><i class="fa fa-check"></i><b>11.4</b> Cleaning up the data</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataRenamingVariables"><i class="fa fa-check"></i><b>11.4.1</b> Renaming variables</a></li>
<li class="chapter" data-level="11.4.2" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataRemovingVariables"><i class="fa fa-check"></i><b>11.4.2</b> Removing variables</a></li>
<li class="chapter" data-level="11.4.3" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataAdjustingVariables"><i class="fa fa-check"></i><b>11.4.3</b> Adjusting variables</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataFinalStepsBeforeAnalysis"><i class="fa fa-check"></i><b>11.5</b> Final steps before analysis</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataFilteringData"><i class="fa fa-check"></i><b>11.5.1</b> Filtering data</a></li>
<li class="chapter" data-level="11.5.2" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataReverseScoring"><i class="fa fa-check"></i><b>11.5.2</b> Reverse-scoring</a></li>
<li class="chapter" data-level="11.5.3" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataCalculatingZScores"><i class="fa fa-check"></i><b>11.5.3</b> Calculating <em>z</em>-scores</a></li>
<li class="chapter" data-level="11.5.4" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataCalculatingCronbachsAlpha"><i class="fa fa-check"></i><b>11.5.4</b> Calculating Cronbach’s alpha</a></li>
<li class="chapter" data-level="11.5.5" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataCreatingACompositeVariable"><i class="fa fa-check"></i><b>11.5.5</b> Creating a composite variable</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Writing</b></span></li>
<li class="chapter" data-level="12" data-path="ReportingResearch.html"><a href="ReportingResearch.html"><i class="fa fa-check"></i><b>12</b> Reporting research</a>
<ul>
<li class="chapter" data-level="12.1" data-path="ReportingResearch.html"><a href="ReportingResearch.html#TheBroaderContext"><i class="fa fa-check"></i><b>12.1</b> The broader context</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="ReportingResearch.html"><a href="ReportingResearch.html#EducationCircles"><i class="fa fa-check"></i><b>12.1.1</b> The education circle</a></li>
<li class="chapter" data-level="12.1.2" data-path="ReportingResearch.html"><a href="ReportingResearch.html#ResearchCircle"><i class="fa fa-check"></i><b>12.1.2</b> The research circle</a></li>
<li class="chapter" data-level="12.1.3" data-path="ReportingResearch.html"><a href="ReportingResearch.html#ResearchGenre"><i class="fa fa-check"></i><b>12.1.3</b> The research genre</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="ReportingResearch.html"><a href="ReportingResearch.html#PurposeOfThisClass"><i class="fa fa-check"></i><b>12.2</b> Purpose of writing in this class</a></li>
<li class="chapter" data-level="12.3" data-path="ReportingResearch.html"><a href="ReportingResearch.html#TheGenreOfScience"><i class="fa fa-check"></i><b>12.3</b> The genre of science</a></li>
<li class="chapter" data-level="12.4" data-path="ReportingResearch.html"><a href="ReportingResearch.html#StyleGuides"><i class="fa fa-check"></i><b>12.4</b> Style guides</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="ReportingResearch.html"><a href="ReportingResearch.html#ApaStyle"><i class="fa fa-check"></i><b>12.4.1</b> APA style</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="ReportingResearch.html"><a href="ReportingResearch.html#IssuesNotExtensivelyCovered"><i class="fa fa-check"></i><b>12.5</b> Issues not extensively covered</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="ReportingResearch.html"><a href="ReportingResearch.html#CriticalThinking"><i class="fa fa-check"></i><b>12.5.1</b> Critical thinking</a></li>
<li class="chapter" data-level="12.5.2" data-path="ReportingResearch.html"><a href="ReportingResearch.html#MechanicsOfWriting"><i class="fa fa-check"></i><b>12.5.2</b> “Grammar,” clarity, and mechanics</a></li>
<li class="chapter" data-level="12.5.3" data-path="ReportingResearch.html"><a href="ReportingResearch.html#PacingTheWritingProcess"><i class="fa fa-check"></i><b>12.5.3</b> Pacing the writing process</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="ReportingResearch.html"><a href="ReportingResearch.html#OutsideHelpOnWritingUpResearch"><i class="fa fa-check"></i><b>12.6</b> Outside help on writing up research</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="ReportingResearch.html"><a href="ReportingResearch.html#research-papers-in-apa-format"><i class="fa fa-check"></i><b>12.6.1</b> Research papers in APA format</a></li>
<li class="chapter" data-level="12.6.2" data-path="ReportingResearch.html"><a href="ReportingResearch.html#WritingUpResearch"><i class="fa fa-check"></i><b>12.6.2</b> Writing up research</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html"><i class="fa fa-check"></i><b>13</b> Writing introductions</a>
<ul>
<li class="chapter" data-level="13.1" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#PurposeOfTheIntroduction"><i class="fa fa-check"></i><b>13.1</b> The purpose of the <em>Introduction</em></a></li>
<li class="chapter" data-level="13.2" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#StructureOfIntroductions"><i class="fa fa-check"></i><b>13.2</b> Structure of introductions</a></li>
<li class="chapter" data-level="13.3" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#ExamplesOfIntroductions"><i class="fa fa-check"></i><b>13.3</b> Examples of introductions</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#ExamplesOfOpeningSentencesOfIntroductions"><i class="fa fa-check"></i><b>13.3.1</b> Examples of opening sentences</a></li>
<li class="chapter" data-level="13.3.2" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#ExamplesOfTheLiteratureReview"><i class="fa fa-check"></i><b>13.3.2</b> Examples of the literature review</a></li>
<li class="chapter" data-level="13.3.3" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#ExamplesOfResearchQuestionsAndHypotheses"><i class="fa fa-check"></i><b>13.3.3</b> Examples of research questions and hypotheses</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#OutsideHelpOnIntroductions"><i class="fa fa-check"></i><b>13.4</b> Outside help on introductions</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#OutsideHelpOnIntroductionsOpeningSentences"><i class="fa fa-check"></i><b>13.4.1</b> Opening sentences</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#PWEFI1"><i class="fa fa-check"></i><b>13.5</b> Practice writing exercise 1</a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#PWEFI1SettingUpGroupsAndDocs"><i class="fa fa-check"></i><b>13.5.1</b> Setting up your groups and docs</a></li>
<li class="chapter" data-level="13.5.2" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#PWEFI1OpeningSentence"><i class="fa fa-check"></i><b>13.5.2</b> Opening sentence</a></li>
<li class="chapter" data-level="13.5.3" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#PWEFI1ResearchQuestion"><i class="fa fa-check"></i><b>13.5.3</b> Research question</a></li>
<li class="chapter" data-level="13.5.4" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#PWEFI1ResearchHypothesis"><i class="fa fa-check"></i><b>13.5.4</b> Research Hypothesis</a></li>
<li class="chapter" data-level="13.5.5" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#PWEFI1GeneralToSpecific"><i class="fa fa-check"></i><b>13.5.5</b> General-to-specific paragraphs</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#PWEFI2"><i class="fa fa-check"></i><b>13.6</b> Practice writing exercise 2</a></li>
<li class="chapter" data-level="13.7" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#WritingAssignment1"><i class="fa fa-check"></i><b>13.7</b> Writing Assignment #1</a>
<ul>
<li class="chapter" data-level="13.7.1" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#GeneralInstructionsOnWritingAssignment1"><i class="fa fa-check"></i><b>13.7.1</b> General Instructions</a></li>
<li class="chapter" data-level="13.7.2" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#SpecificInstructionsOnWritingAssignment1"><i class="fa fa-check"></i><b>13.7.2</b> Specific Instructions</a></li>
<li class="chapter" data-level="13.7.3" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#UploadingRoughDraftOfWritingAssignment1"><i class="fa fa-check"></i><b>13.7.3</b> Uploading the rough draft</a></li>
<li class="chapter" data-level="13.7.4" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#uploading-the-final-draft"><i class="fa fa-check"></i><b>13.7.4</b> Uploading the final draft</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html"><i class="fa fa-check"></i><b>14</b> Writing <em>Method</em> sections</a>
<ul>
<li class="chapter" data-level="14.1" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#PurposeOfTheMethodSection"><i class="fa fa-check"></i><b>14.1</b> Purpose of the Method section</a></li>
<li class="chapter" data-level="14.2" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#StructureOfMethodSections"><i class="fa fa-check"></i><b>14.2</b> Structure of Method sections</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#MethodSection1Participants"><i class="fa fa-check"></i><b>14.2.1</b> <em>Participants</em></a></li>
<li class="chapter" data-level="14.2.2" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#MethodSection2Materials"><i class="fa fa-check"></i><b>14.2.2</b> <em>Materials</em></a></li>
<li class="chapter" data-level="14.2.3" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#MethodSection3DesignAndAnalysis"><i class="fa fa-check"></i><b>14.2.3</b> <em>Design and Analysis</em></a></li>
<li class="chapter" data-level="14.2.4" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#MethodSection4Procedure"><i class="fa fa-check"></i><b>14.2.4</b> <em>Procedure</em></a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#OutsideHelpOnMethodsSections"><i class="fa fa-check"></i><b>14.3</b> Outside help on Method sections</a></li>
<li class="chapter" data-level="14.4" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#PWEFM1"><i class="fa fa-check"></i><b>14.4</b> Practice writing exercise 1</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#PWEFM1Participants"><i class="fa fa-check"></i><b>14.4.1</b> Participants</a></li>
<li class="chapter" data-level="14.4.2" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#PWEFM1MaterialsDesignProcedures"><i class="fa fa-check"></i><b>14.4.2</b> Materials, Design, and Procedures</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#WritingAssignment2"><i class="fa fa-check"></i><b>14.5</b> Writing Assignment #2</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#GeneralInstructionsOnWritingAssignment2"><i class="fa fa-check"></i><b>14.5.1</b> General Instructions</a></li>
<li class="chapter" data-level="14.5.2" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#SpecificInstructionsOnWritingAssignment2"><i class="fa fa-check"></i><b>14.5.2</b> Specific Instructions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html"><i class="fa fa-check"></i><b>15</b> Writing <em>Results</em> sections</a>
<ul>
<li class="chapter" data-level="15.1" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html#NoteOnWritingAssignments3And4"><i class="fa fa-check"></i><b>15.1</b> A note on Writing Assignments 3 and 4</a></li>
<li class="chapter" data-level="15.2" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html#StructureOfResultsSections"><i class="fa fa-check"></i><b>15.2</b> Structure of <em>Results</em> sections</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html#ExamplesOfResultsSections"><i class="fa fa-check"></i><b>15.2.1</b> Examples of <em>Results</em> sections</a></li>
<li class="chapter" data-level="15.2.2" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html#FormattingTablesInAPA"><i class="fa fa-check"></i><b>15.2.2</b> Formatting tables in APA</a></li>
<li class="chapter" data-level="15.2.3" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html#FormattingFiguresInAPA"><i class="fa fa-check"></i><b>15.2.3</b> Formatting figures in APA</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html#PWEFR"><i class="fa fa-check"></i><b>15.3</b> Practice writing exercise</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html#PWEFRFormingGroups"><i class="fa fa-check"></i><b>15.3.1</b> Forming groups</a></li>
<li class="chapter" data-level="15.3.2" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html#PWEFRGetStatisticalOutputReady"><i class="fa fa-check"></i><b>15.3.2</b> Get the statistical output ready</a></li>
<li class="chapter" data-level="15.3.3" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html#PWEFRWriting"><i class="fa fa-check"></i><b>15.3.3</b> Writing</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html"><i class="fa fa-check"></i><b>16</b> Writing <em>Discussion</em> sections</a>
<ul>
<li class="chapter" data-level="16.1" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#StructureOfDiscussionSections"><i class="fa fa-check"></i><b>16.1</b> Purpose and structure of <em>Discussion</em> sections</a>
<ul>
<li class="chapter" data-level="16.1.1" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#StructureOfSingleStudyDiscussionSections"><i class="fa fa-check"></i><b>16.1.1</b> Single-study <em>Discussion</em> sections</a></li>
<li class="chapter" data-level="16.1.2" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#StructureOfMultipleStudyDiscussionSections"><i class="fa fa-check"></i><b>16.1.2</b> Multiple-study <em>Discussion</em> sections</a></li>
<li class="chapter" data-level="16.1.3" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#ExamplesOfDiscussionSections"><i class="fa fa-check"></i><b>16.1.3</b> Examples of <em>Discussion</em> sections</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#PWEFD"><i class="fa fa-check"></i><b>16.2</b> Practice writing exercise</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#PWEFDGettingReady"><i class="fa fa-check"></i><b>16.2.1</b> Getting ready</a></li>
<li class="chapter" data-level="16.2.2" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#PWEFDWriting"><i class="fa fa-check"></i><b>16.2.2</b> Writing</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#WritingAssignment3"><i class="fa fa-check"></i><b>16.3</b> Writing Assignment #3</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#GeneralInstructionsOnWritingAssignment3"><i class="fa fa-check"></i><b>16.3.1</b> General Instructions</a></li>
<li class="chapter" data-level="16.3.2" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#SpecificInstructionsOnWritingAssignment3"><i class="fa fa-check"></i><b>16.3.2</b> Specific Instructions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html"><i class="fa fa-check"></i><b>17</b> Writing <em>General Discussion</em> sections</a>
<ul>
<li class="chapter" data-level="17.1" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#NoteOnWritingAssignments4"><i class="fa fa-check"></i><b>17.1</b> A note on Writing Assignment 4</a></li>
<li class="chapter" data-level="17.2" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#StructureOfGeneralDiscussionSections"><i class="fa fa-check"></i><b>17.2</b> Structure of <em>General Discussion</em> sections</a></li>
<li class="chapter" data-level="17.3" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#ContentsOfGeneralDiscussionSections"><i class="fa fa-check"></i><b>17.3</b> Contents of <em>General Discussion</em> sections</a>
<ul>
<li class="chapter" data-level="17.3.1" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#ContentsOfGeneralDiscussionSectionsSynthesizing"><i class="fa fa-check"></i><b>17.3.1</b> Synthesizing</a></li>
<li class="chapter" data-level="17.3.2" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#ContentsOfGeneralDiscussionSectionsClarifying"><i class="fa fa-check"></i><b>17.3.2</b> Clarifying</a></li>
<li class="chapter" data-level="17.3.3" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#ContentsOfGeneralDiscussionSectionsConcluding"><i class="fa fa-check"></i><b>17.3.3</b> Concluding</a></li>
<li class="chapter" data-level="17.3.4" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#ExampleInAppendixI"><i class="fa fa-check"></i><b>17.3.4</b> Example in Appendix I</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#PWEFGD"><i class="fa fa-check"></i><b>17.4</b> Practice writing exercise</a>
<ul>
<li class="chapter" data-level="17.4.1" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#PWEFGDGettingReady"><i class="fa fa-check"></i><b>17.4.1</b> Getting ready</a></li>
<li class="chapter" data-level="17.4.2" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#PWEFGDWriting"><i class="fa fa-check"></i><b>17.4.2</b> Writing</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#WritingAssignment4"><i class="fa fa-check"></i><b>17.5</b> Writing Assignment #4</a>
<ul>
<li class="chapter" data-level="17.5.1" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#GeneralInstructionsOnWritingAssignment4"><i class="fa fa-check"></i><b>17.5.1</b> General Instructions</a></li>
<li class="chapter" data-level="17.5.2" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#SpecificInstructionsOnWritingAssignment4"><i class="fa fa-check"></i><b>17.5.2</b> Specific Instructions</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendixes</b></span></li>
<li><a href="a-introduction-example.html#a-introduction-example">A: <em>Introduction</em> example</a></li>
<li><a href="b-introduction-rubric.html#b-introduction-rubric">B: <em>Introduction</em> rubric</a></li>
<li><a href="c-methods-example.html#c-methods-example">C: <em>Methods</em> example</a></li>
<li><a href="d-method-rubric.html#d-method-rubric">D: <em>Method</em> rubric</a></li>
<li><a href="e-results-example.html#e-results-example">E: <em>Results</em> example</a></li>
<li><a href="f-results-rubric.html#f-results-rubric">F: <em>Results</em> rubric</a></li>
<li><a href="g-discussion-example.html#g-discussion-example">G: <em>Discussion</em> example</a></li>
<li><a href="h-discussion-rubric.html#h-discussion-rubric">H: <em>Discussion</em> rubric</a></li>
<li><a href="i-general-discussion-example.html#i-general-discussion-example">I: <em>General Discussion</em> example</a></li>
<li><a href="j-general-discussion-rubric.html#j-general-discussion-rubric">J: <em>General Discussion</em> rubric</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
    sharing:

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Lab Manual for PSYC 301: Elementary Statistics for Psychology</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="CategoricalDataAnalysis" class="section level1" number="5">
<h1><span class="header-section-number">Chapter 5</span> Categorical data analysis</h1>
<p>Up to this point, we have been following, roughly, the order of information set out in your main textbook by <span class="citation"><a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft</a> (<a href="#ref-lsj" role="doc-biblioref">2019</a>)</span>. We depart a little at this point as we are not going to cover the material in Chapter 6 of that book. We will cover that material in Appendix A. Nor will we cover chapter 7-9 at all. Instead, this lab manual resumes below as parallel to Chapter 10 of <span class="citation"><a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft</a> (<a href="#ref-lsj" role="doc-biblioref">2019</a>)</span>.</p>
<p>From the current chapter (Chapters <a href="CategoricalDataAnalysis.html#CategoricalDataAnalysis">5</a>) to Chapter <a href="FactorialAnova.html#FactorialAnova">9</a>, you’ll see that the point of inferential statistics is to calculate specific signal-to-noise ratios in order to see if the signal that emerges from our data is so strong over the noise (that emerges from our data) that we can confidently claim that we indeed have a signal, and not just a bunch of noise.</p>
<p>We will start with the first of these tests: the <em>chi-square test</em>. Thus, this chapter shows you how to use jamovi to conduct analyses when your outcome variable consists of counts of nominal (categorical) data (e.g., the number of men vs. women who voted in a particular district, where the proportions are known to be about 50/50). The topic is covered in much more detail in your main textbook <span class="citation"><a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft</a> (<a href="#ref-lsj" role="doc-biblioref">2019</a>Chapter 10)</span>.</p>
<p>There are several versions of the chi-square test, but we will only cover two here: the <span class="math inline">\(\chi^2\)</span> <em>goodness-of-fit test</em>, and the <span class="math inline">\(\chi^2\)</span> <em>test of association</em>. The former is used is when you want to compare your sample data to known population proportions (like the voting example above), and the latter is when you want to compare the counts of two groups against one another. For example, perhaps you wanted to know whether the morning-beverage preferences (coffee, tea, or juice) were the same across men and women. A <span class="math inline">\(\chi^2\)</span> test of association could answer this (assuming you collected the data, of course).</p>
<p>The first we will cover here is the goodness-of-fit test.</p>
<p><br/></p>
<div id="ChiSquareGoodnessOfFit" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Chi-square goodness-of-fit test</h2>
<p>In each chapter in this manual, there will be one basic analysis, and often, one, more advanced analysis. The basic analysis will always be a quick way to do the analysis presented in the relevant chapter in <span class="citation"><a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft</a> (<a href="#ref-lsj" role="doc-biblioref">2019</a>)</span>. The more advanced analysis will be the UC Berkeley graduate-admissions data from 1973 (a famous data-analysis case).</p>
<p><br/></p>
<div id="ChiSquareGoodnessOfFitBasicCards" class="section level3" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> Basic: The Cards data</h3>
<p>This is from Section 10.1.1 of <span class="citation"><a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft</a> (<a href="#ref-lsj" role="doc-biblioref">2019</a>)</span>, and the data set is labeled <em>Randomness.csv</em>. Thus: <span class="math inline">\((\equiv)\)</span> &gt; <em>Open</em> &gt; <em>Data Library</em> &gt; <em>learning statistics with jamovi</em> &gt; <em>randomness.csv</em>.</p>
<p>In this imaginary experiment (with imaginary data), participants were asked to mentally choose a single card from an imagined deck of cards, and then a second card. The idea was to figure out if people really could do things at random, or if they had preferences for different suits (<em>clubs</em>, <em>diamonds</em>, <em>hearts</em>, or <em>spades</em>).</p>
<p><br/></p>
<div id="ChiSquareGoodnessOfFitBasicCardsInspecting" class="section level4" number="5.1.1.1">
<h4><span class="header-section-number">5.1.1.1</span> Inspecting</h4>
<p>To start, you just want to get a bird’s-eye view of the relative proportions across the two choices. So you to go <em>Exploration</em> &gt; <em>Descriptives</em>, drag the first choice over to the <em>Variables</em> box and check <em>Frequency tables</em>. We also unchecked all the other options for descriptive statistics. You should see what is below in Figure (<a href="CategoricalDataAnalysis.html#fig:ChisquareGoodFitTestChoice1FrequencyTable">5.1</a>).</p>
<p><br/></p>
<div class="figure"><span id="fig:ChisquareGoodFitTestChoice1FrequencyTable"></span>
<img src="images/CategoricalData/ChisquareGoodFitTestChoice1FrequencyTable.png" alt="Setting the parameters in jamovi for getting the counts on the first choice of the *cards* data from @lsj." width="600px" />
<p class="caption">
Figure 5.1: Setting the parameters in jamovi for getting the counts on the first choice of the <em>cards</em> data from <span class="citation"><a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft</a> (<a href="#ref-lsj" role="doc-biblioref">2019</a>)</span>.
</p>
</div>
<p><br/></p>
<p>Your output should look like the following:</p>
<p><br/></p>
<pre><code>## 
##  DESCRIPTIVES
## 
##  FREQUENCIES
## 
##  Frequencies of choice_1                              
##  ──────────────────────────────────────────────────── 
##    Levels      Counts    % of Total    Cumulative %   
##  ──────────────────────────────────────────────────── 
##    clubs           35      17.50000        17.50000   
##    diamonds        51      25.50000        43.00000   
##    hearts          64      32.00000        75.00000   
##    spades          50      25.00000       100.00000   
##  ────────────────────────────────────────────────────</code></pre>
<p><br/></p>
<p>It looks like people have a preference for <em>hearts</em> over <em>clubs</em>, but this could be due to chance. We need to test this.</p>
<p><br/></p>
</div>
<div id="ChiSquareGoodnessOfFitBasicCardsHypothesizing" class="section level4" number="5.1.1.2">
<h4><span class="header-section-number">5.1.1.2</span> Hypothesizing</h4>
<p>So referring to Chapter 9 in <span class="citation"><a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft</a> (<a href="#ref-lsj" role="doc-biblioref">2019</a>)</span>, first we need to create null and research hypotheses. Stated in English, it would be as follows:</p>
<blockquote>
<p><span class="math inline">\(H_0:\)</span> There is no suit preference among participants</p>
</blockquote>
<p><br/></p>
<p>Mathematically, it would come out as below, where we state each outcome as a probability, <em>P</em>:</p>
<blockquote>
<p><span class="math inline">\(H_0:P_{clubs}=P_{diamonds}=P_{hearts}=P_{spades}\)</span></p>
</blockquote>
<p><br/></p>
<p>Or even better for this particular inferential test:</p>
<blockquote>
<p><span class="math inline">\(H_0:P=(.25, .25, .25, .25)\)</span></p>
</blockquote>
<p><br/></p>
<p>This last one means that you are predicting that the probability for each suit is equal.</p>
<p><br/></p>

<div class="rmdimportant">
<strong><em>IMPORTANT</em></strong>: In this chi-square goodness-of-fit test, all the probabilities were presumably equal at 25% each. But this isn’t always the case. For instance, if we had asked participants to imagine any card ignoring the suit (<em>clubs</em>, <em>diamonds</em>, <em>hearts</em>, and <em>spades</em>) but including jokers, then the probabilities under the null hypothesis would be 4/54 (or 7.41%) for each of the values 2-10, <em>Jack</em>, <em>Queen</em>, <em>King</em>, and <em>Ace</em>, but only 2/54 (or 3.7%) for a <em>Joker</em>. The chi-square goodness-of-fit test can account for these differences. You will see this in the advanced analysis in section <a href="CategoricalDataAnalysis.html#ChiSquareGoodnessOfFitAdvancedUCBAdmit">5.1.2</a>, if you choose to do so. This is also covered in <span class="citation"><a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft</a> (<a href="#ref-lsj" role="doc-biblioref">2019</a>)</span> in section 10.1.8.
</div>
<p><br/></p>
<p>Conversely, the research hypothesis would be as follows:</p>
<blockquote>
<p><span class="math inline">\(H_1\)</span>: Participants have a preference for one or more of the suits over one or more of the others</p>
</blockquote>
<blockquote>
<p><span class="math inline">\(H_1:P \neq (.25, .25, .25, .25)\)</span></p>
</blockquote>
<p><br/></p>

<div class="rmdimportant">
<strong><em>IMPORTANT</em></strong>: The research hypothesis above is not very specific. It can also be stated in English as <em>any outcome that is not the null-hypothesis outcome</em>. This formulation is appropriate when there more than two things to compare. This is because it could be true that <span class="math inline">\(P_{clubs} \neq P_{spades}\)</span>, or <span class="math inline">\(P_{clubs} \neq (P_{diamonds}=P_{hearts}=P_{spades})\)</span>, or even <span class="math inline">\((P_{clubs} =P_{diamonds}) \neq (P_{hearts}=P_{spades})\)</span>. Clearly, there are several possible outcomes for the research hypothesis. You simply need to infer these underlying possibilities when reading the research hypothesis since it would be onerous to write all of them out. That said, there are cases where you do write them out (in which case they then become specific predictions). This issue will come up again and again, especially when we get to ANOVAs.
</div>
<p><br/></p>
</div>
<div id="ChiSquareGoodnessOfFitBasicCardsTesting" class="section level4" number="5.1.1.3">
<h4><span class="header-section-number">5.1.1.3</span> Testing</h4>
<p>Carrying out the chi-square goodness-of-fit test is ultimately quite easy in jamovi. But we will spend a little extra time explaining the results since this is the first inferential test in the lab manual.</p>
<p>To carry out the test, Go to the <em>Analyses</em> tab across the top, click <em>Frequencies</em>, and then choose <em>N Outcomes</em> <span class="math inline">\(\chi^2\)</span> <em>Goodness of fit</em>. This is shown in the screenshot below, Figure <a href="CategoricalDataAnalysis.html#fig:ChisquareGoodFitChooseFromPullDown">5.2</a>.</p>
<div class="figure"><span id="fig:ChisquareGoodFitChooseFromPullDown"></span>
<img src="images/CategoricalData/ChisquareGoodFitChooseFromPullDown.png" alt="Choosing the chi-square goodness-of-fit test from the *Frequencies* menu in jamovi." width="600px" />
<p class="caption">
Figure 5.2: Choosing the chi-square goodness-of-fit test from the <em>Frequencies</em> menu in jamovi.
</p>
</div>
<p><br/></p>
<p>Then slide the variable <em>choice_1</em> over to the <em>Variable</em> box. Also click the <em>Expected counts</em> box. The parameters should be as you see below in Figure <a href="CategoricalDataAnalysis.html#fig:ChisquareGoodFitTestChoice1Parameters">5.3</a>.</p>
<p><br/></p>
<div class="figure"><span id="fig:ChisquareGoodFitTestChoice1Parameters"></span>
<img src="images/CategoricalData/ChisquareGoodFitTestChoice1Parameters.png" alt="Setting the parameters in jamovi for doing the chi-square goodness-of-fit test on first choice of the *cards* data from @lsj." width="600px" />
<p class="caption">
Figure 5.3: Setting the parameters in jamovi for doing the chi-square goodness-of-fit test on first choice of the <em>cards</em> data from <span class="citation"><a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft</a> (<a href="#ref-lsj" role="doc-biblioref">2019</a>)</span>.
</p>
</div>
<p><br/></p>
<p>The output should look like the following:</p>
<p><br/></p>
<pre><code>## 
##  PROPORTION TEST (N OUTCOMES)
## 
##  Proportions - choice_1                             
##  ────────────────────────────────────────────────── 
##    Level                   Count       Proportion   
##  ────────────────────────────────────────────────── 
##    clubs       Observed          35     0.1750000   
##                Expected    50.00000     0.2500000   
##                                                     
##    diamonds    Observed          51     0.2550000   
##                Expected    50.00000     0.2500000   
##                                                     
##    hearts      Observed          64     0.3200000   
##                Expected    50.00000     0.2500000   
##                                                     
##    spades      Observed          50     0.2500000   
##                Expected    50.00000     0.2500000   
##  ────────────────────────────────────────────────── 
## 
## 
##  χ² Goodness of Fit              
##  ─────────────────────────────── 
##    χ²          df    p           
##  ─────────────────────────────── 
##    8.440000     3    0.0377419   
##  ───────────────────────────────</code></pre>
<p><br/></p>
<p>You might also want to plot this in jamovi. The way to do this is by checking the <em>Barplot</em> box in <em>Descriptives</em>. See Figure <a href="CategoricalDataAnalysis.html#fig:ChisquareGoodFitTestChoice1BarplotParameters">5.4</a> below for the right parameter settings.</p>
<p><br/></p>
<div class="figure"><span id="fig:ChisquareGoodFitTestChoice1BarplotParameters"></span>
<img src="images/CategoricalData/ChisquareGoodFitTestChoice1BarplotParameters.png" alt="Setting the parameters in jamovi for creating a barplot for the first choice of the *cards* data from @lsj." width="600px" />
<p class="caption">
Figure 5.4: Setting the parameters in jamovi for creating a barplot for the first choice of the <em>cards</em> data from <span class="citation"><a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft</a> (<a href="#ref-lsj" role="doc-biblioref">2019</a>)</span>.
</p>
</div>
<p><br/></p>
<p>The results will look like the following:</p>
<p><br/></p>
<pre><code>## 
##  DESCRIPTIVES</code></pre>
<p><img src="ElemStatsLabManual_files/figure-html/unnamed-chunk-72-1.svg" width="672" /></p>
<p><br/></p>
</div>
<div id="ChiSquareGoodnessOfFitBasicCardsInterpretingOutput" class="section level4" number="5.1.1.4">
<h4><span class="header-section-number">5.1.1.4</span> Interpreting</h4>
<p>First, note that since we asked for <em>Expected counts</em>, jamovi told use the exact numbers that would have been expected under the null hypothesis. This was 50 for each group since there were a total of 200 participants, and we assumed that there was an equal chance of any card suit being preferred (25% for each suit).</p>
<p>The observed values are the counts that we actually got from the participants.</p>
<p>This is all easy enough to read from the first table. The second table gives us the results of the inferential test.</p>
<p>The degrees of freedom is for the chi-square goodness-of-fit test is the total number of categories minus 1. There were 4 card suits, minus 1, therefore, df = 3. The test statistic gave us an obtained value of 8.44. The test statistic is the following formula:</p>
<p><br/></p>
<p><span class="math display">\[\chi^2=\sum_{i=1}^{k}\frac{(O_{i}-E_{i})^2}{E_i}\]</span></p>
<p><br/></p>
<p>The obtained value is 8.44, which is what you get after you refer to the table above, and substitute the <em>O</em>s and the <em>E</em>s with the <em>Observed</em> and <em>Expected</em> values (respectively) for each card suit (<em>i</em>) found in the table above, .</p>
<p>What is important about the degrees of freedom (3 in this case) is that this figure sets up the particular chi-squared <strong>distribution</strong> that the test statistics of 8.44 will be evaluated against. This distribution is the solid line in Figure 10.1 in <span class="citation"><a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft</a> (<a href="#ref-lsj" role="doc-biblioref">2019, sec. 10.1.5</a>, p. 217)</span>. But we reproduce it below.</p>
<p><br/></p>
<p><img src="ElemStatsLabManual_files/figure-html/unnamed-chunk-73-1.svg" width="672" /></p>
<p><br/></p>
<p>What does this distribution represent? Think of it this way: If you carried out an infinite number of these experiments with the cards and the four suits, this <span class="math inline">\(\chi_2\)</span> distribution (with degrees of freedom equal to 3) represents the relative probabilities (areas under the curve) of getting different ranges of observed values (mapped across the x-axis) under the assumption that the null hypothesis is underlyingly true.</p>
<p>It turns out that for this inferential test (<span class="math inline">\(\chi^2\)</span> goodness of fit) with three degrees of freedom, obtained values of 7.815 or greater would be less than 5% likely to occur if the null hypothesis were true. The value 7.815 is the critical value, where that 5% area extending out to the right starts. Our obtained value of 8.44 is greater than that (7.815) of course. In fact, if we were to calculate the area under the curve to the right of 8.44, we would get 3.8%, which is our <em>p</em>-value up above (an <em>exact</em> <em>p</em>-value).</p>
<p>Our <em>p</em>-value is less than our pre-set <span class="math inline">\(\alpha\)</span> (alpha) level of .05, so we are given the “green light” to reject the null hypothesis. What does that actually mean?</p>
<p>Normally, one doesn’t talk about rejecting the null hypothesis, per se. Rather, the expression <strong><em>was statistically significant</em></strong> suffices because it is shorthand for a more complex process that all researchers are assumed to understand. What is this process. By way of illustration, here is an overwrought, but accurate way of rejecting the null hypothesis:</p>
<blockquote>
<p>The obtained value for our chi-square goodness-of-fit test was 8.44. If we replicated this exact experiment an infinite number of times with new samples (thereby giving us 3 degrees of freedom each time) <strong><em>and</em></strong> the null hypothesis were underlyingly true, then obtained values of 8.44 or greater would occur only about 3.8% of the time. Since it is the industry standard in Psychology not to accept a risk of being wrong greater than 5%, we are comfortable accepting the 3.8% risk here, thus concluding (at least provisionally) that it’s not our data that are strange, but rather that the null hypothesis itself. That is, it seems to be an inappropriate assumption in this case, so we provisionally reject it. Something <strong><em>other</em></strong> than the null hypothesis is more likely to be true, namely (assuming we have designed things appropriately), the research hypothesis. Since there are more than 2 categories (df&gt;1), the exact form of the research hypothesis still needs to be determined. This may be determined either through post-hoc or planned comparisons.</p>
</blockquote>
<p><br/></p>

<div class="rmdwarning">
<strong><em>WARNING</em></strong>: We noted above that this passsage is overwrought. Do not ever write such a thing (though we think maybe researchers should practice it to remind themselves what they are doing). It is also pedantic and condescending since any researcher reading such a passage should already understand that this is the actual meaning that undergirds <em>statistical significance</em>.
</div>
<p><br/></p>
</div>
<div id="ChiSquareGoodnessOfFitBasicCardsReporting" class="section level4" number="5.1.1.5">
<h4><span class="header-section-number">5.1.1.5</span> Reporting</h4>
<p>Actually writing out results takes a far different form.</p>
<p>Here, we will briefly discuss how to write out the results of statistics in APA format since this is the first time we cover it in the lab manual. But a more detailed account is provided in section <a href="ReportingResearch.html#ReportingInferentialStatistics">12.4.1.3.2</a>.</p>
<p>Test statistics in APA format always follow the pattern below.</p>
<ol style="list-style-type: decimal">
<li>a letter (in italics) representing the test statistic used</li>
<li>parentheses that enclose the degrees of freedom</li>
<li>an equals sign</li>
<li>the obtained value of the test statistic</li>
<li>a comma</li>
<li>the letter <em>p</em> in italics</li>
<li>one of three symbols: =, &lt;, or &gt;</li>
<li>a <em>p</em>-value</li>
</ol>
<p><br/></p>
<p>Thus, the results of our chi-square analysis would be reported as <span class="math inline">\(\chi^2 (3)=8.44,p=.038\)</span>.</p>
<p><br/></p>
<p>But we cannot stop there. A proper report in a results section only includes the test results as parentheticals to more everyday prose.</p>
<blockquote>
<p>Our results were statistically significant, <span class="math inline">\(\chi^2 (3)=8.44,p=.038\)</span>. It appears that when people imagine a card picked randomly from a deck of cards, they have preferences for certain suits over others. For whatever reason, the most likely candidate disproportionality in our case is that they have a strong inclination to imagine a card from <em>hearts</em> (32%) and a strong disinclination to imagine a card with <em>clubs</em> (17.5%). The other two suits had observed frequencies that matched their expected frequencies. A post-hoc analysis would be required to determine the exact relationships with more certainty.</p>
</blockquote>
<p><br/></p>

<div class="rmdnote">
<strong>NOTE</strong>: This first sentence in the passage above is actually a condensed version of almost the entire “overwrought” passage above that (i.e., the one above the WARNING message).
</div>
<p><br/></p>
</div>
</div>
<div id="ChiSquareGoodnessOfFitAdvancedUCBAdmit" class="section level3" number="5.1.2">
<h3><span class="header-section-number">5.1.2</span> Advanced: Student admissions at UC Berkeley</h3>
<p>For the more advanced analysis, we will work with a well-known data set from <span class="citation"><a href="#ref-BickelHammelOconnell1975" role="doc-biblioref">Bickel, Hammel, &amp; O’Connell</a> (<a href="#ref-BickelHammelOconnell1975" role="doc-biblioref">1975</a>)</span> that analyzed the 1973 graduate-school admissions data to the University of California - Berkeley. The data set contains data on how many men vs. women were given or denied admission across the six largest graduate schools at <em>Cal</em> (<em>Cal</em> is the nickname for the university).</p>
<p>At first blush, it looks like men are being favored over women in graduate admissions. But we want to find out whether this is really true.</p>
<p><br/></p>
<div id="UCBAdmissionsOpeningData" class="section level4" number="5.1.2.1">
<h4><span class="header-section-number">5.1.2.1</span> Opening data</h4>
<p>This data set is available as one of the data sets that comes with base-R. Since jamovi is built on top of R, it has no problem opening R data sets. In fact, the module called <strong>R data sets</strong> includes this data set. Install this module if you haven’t already (see the end of Section <a href="GettingUsedtoJamovi.html#NavigatingJamovi">1.2</a> for how to do this).</p>
<p>Once you have done this, all you have to do is click <span class="math inline">\((\equiv)\)</span> &gt; <em>Open</em> &gt; <em>Data library</em> &gt; <em>R data sets</em> &gt; <em>UCBAdmissions</em> (the file is near the bottom of the list). Your data should look like what is below.</p>
<p><br/></p>
<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-77">Table 5.1: </span>Graduate-school admissions figures by gender and department from the University of California Berkeley in 1973 (available as the ‘UCBAdmissions’ sample data set in base-R).
</caption>
<thead>
<tr>
<th style="text-align:left;">
Admit
</th>
<th style="text-align:left;">
Gender
</th>
<th style="text-align:left;">
Dept
</th>
<th style="text-align:right;">
Freq
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Admitted
</td>
<td style="text-align:left;">
Male
</td>
<td style="text-align:left;">
A
</td>
<td style="text-align:right;">
512
</td>
</tr>
<tr>
<td style="text-align:left;">
Rejected
</td>
<td style="text-align:left;">
Male
</td>
<td style="text-align:left;">
A
</td>
<td style="text-align:right;">
313
</td>
</tr>
<tr>
<td style="text-align:left;">
Admitted
</td>
<td style="text-align:left;">
Female
</td>
<td style="text-align:left;">
A
</td>
<td style="text-align:right;">
89
</td>
</tr>
<tr>
<td style="text-align:left;">
Rejected
</td>
<td style="text-align:left;">
Female
</td>
<td style="text-align:left;">
A
</td>
<td style="text-align:right;">
19
</td>
</tr>
<tr>
<td style="text-align:left;">
Admitted
</td>
<td style="text-align:left;">
Male
</td>
<td style="text-align:left;">
B
</td>
<td style="text-align:right;">
353
</td>
</tr>
<tr>
<td style="text-align:left;">
Rejected
</td>
<td style="text-align:left;">
Male
</td>
<td style="text-align:left;">
B
</td>
<td style="text-align:right;">
207
</td>
</tr>
<tr>
<td style="text-align:left;">
Admitted
</td>
<td style="text-align:left;">
Female
</td>
<td style="text-align:left;">
B
</td>
<td style="text-align:right;">
17
</td>
</tr>
<tr>
<td style="text-align:left;">
Rejected
</td>
<td style="text-align:left;">
Female
</td>
<td style="text-align:left;">
B
</td>
<td style="text-align:right;">
8
</td>
</tr>
<tr>
<td style="text-align:left;">
Admitted
</td>
<td style="text-align:left;">
Male
</td>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
120
</td>
</tr>
<tr>
<td style="text-align:left;">
Rejected
</td>
<td style="text-align:left;">
Male
</td>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
205
</td>
</tr>
<tr>
<td style="text-align:left;">
Admitted
</td>
<td style="text-align:left;">
Female
</td>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
202
</td>
</tr>
<tr>
<td style="text-align:left;">
Rejected
</td>
<td style="text-align:left;">
Female
</td>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
391
</td>
</tr>
<tr>
<td style="text-align:left;">
Admitted
</td>
<td style="text-align:left;">
Male
</td>
<td style="text-align:left;">
D
</td>
<td style="text-align:right;">
138
</td>
</tr>
<tr>
<td style="text-align:left;">
Rejected
</td>
<td style="text-align:left;">
Male
</td>
<td style="text-align:left;">
D
</td>
<td style="text-align:right;">
279
</td>
</tr>
<tr>
<td style="text-align:left;">
Admitted
</td>
<td style="text-align:left;">
Female
</td>
<td style="text-align:left;">
D
</td>
<td style="text-align:right;">
131
</td>
</tr>
<tr>
<td style="text-align:left;">
Rejected
</td>
<td style="text-align:left;">
Female
</td>
<td style="text-align:left;">
D
</td>
<td style="text-align:right;">
244
</td>
</tr>
<tr>
<td style="text-align:left;">
Admitted
</td>
<td style="text-align:left;">
Male
</td>
<td style="text-align:left;">
E
</td>
<td style="text-align:right;">
53
</td>
</tr>
<tr>
<td style="text-align:left;">
Rejected
</td>
<td style="text-align:left;">
Male
</td>
<td style="text-align:left;">
E
</td>
<td style="text-align:right;">
138
</td>
</tr>
<tr>
<td style="text-align:left;">
Admitted
</td>
<td style="text-align:left;">
Female
</td>
<td style="text-align:left;">
E
</td>
<td style="text-align:right;">
94
</td>
</tr>
<tr>
<td style="text-align:left;">
Rejected
</td>
<td style="text-align:left;">
Female
</td>
<td style="text-align:left;">
E
</td>
<td style="text-align:right;">
299
</td>
</tr>
<tr>
<td style="text-align:left;">
Admitted
</td>
<td style="text-align:left;">
Male
</td>
<td style="text-align:left;">
F
</td>
<td style="text-align:right;">
22
</td>
</tr>
<tr>
<td style="text-align:left;">
Rejected
</td>
<td style="text-align:left;">
Male
</td>
<td style="text-align:left;">
F
</td>
<td style="text-align:right;">
351
</td>
</tr>
<tr>
<td style="text-align:left;">
Admitted
</td>
<td style="text-align:left;">
Female
</td>
<td style="text-align:left;">
F
</td>
<td style="text-align:right;">
24
</td>
</tr>
<tr>
<td style="text-align:left;">
Rejected
</td>
<td style="text-align:left;">
Female
</td>
<td style="text-align:left;">
F
</td>
<td style="text-align:right;">
317
</td>
</tr>
</tbody>
</table>
<p><br/></p>
<p>The data give us the numbers of men versus women who were admitted and rejected by academic department (the six largest departments only). We have what we need to start an analysis of whether men are being favored over women in admissions.</p>
<p><br/></p>
</div>
<div id="UCBAdmissionsPreparing" class="section level4" number="5.1.2.2">
<h4><span class="header-section-number">5.1.2.2</span> Preparing</h4>
<p>There are two things that you are going to need to do in order to prepare this data for a full analysis:</p>
<ol style="list-style-type: decimal">
<li>Calculate relative proportions of men versus women who <strong><em>applied</em></strong> to graduate school at Cal; and</li>
<li>Filter the data in order to count admissions only, as well as filter by department in six of the cases (Departments A-F).</li>
</ol>
<p><br/></p>
<div id="UCBAdmissionsCalculateRelativeProportions" class="section level5" number="5.1.2.2.1">
<h5><span class="header-section-number">5.1.2.2.1</span> Calculating relative proportions</h5>
<p>The default null hypothesis for a chi-square goodness-of-fit test is that all outcomes are equally likely.<a href="#fn54" class="footnote-ref" id="fnref54"><sup>54</sup></a> So in the admissions data we have, it would assume that men and women are equally likely to be admitted (50/50); the analysis would expect equal numbers of men and women admitted under the null hypothesis.</p>
<p>There is a big problem with the admissions data at Cal, however. Namely, not only did the numbers of men vs. women who applied to graduate school at the university differ overall (2,691 vs. 1,835), but the numbers also differed by department. So if more men apply than women, you’d expect more men to be accepted than women, even if the university (or department) is admitting men and women without bias towards one or the other. In fact, if equal numbers of men and women were accepted, you’d likely have to conclude that the university was favoring women in admissions.</p>
<p>As noted in <span class="citation"><a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft</a> (<a href="#ref-lsj" role="doc-biblioref">2019, sec. 10.1.8</a>)</span>, this test offers a way to correct for this. We will need to do so here. To start, we will need to carry out some <em>Descriptives</em> on the data. First, we go to the <em>Analysis</em> tab, and click <em>Descriptives.</em> We move the variable <em>Freq</em> over to the <em>Variables</em> box, and the variable <em>Gender</em> over to the <em>Split by</em> box. Then we make sure that the only box that is checked is <em>Sum</em> under <em>Central Tendency</em>. This will add up the numbers for Admitted and Rejected applicants across all departments, but divided by <em>Gender</em>. See Figure <a href="CategoricalDataAnalysis.html#fig:ChisquareGoodFitSumMenWomenAcrossUniversity">5.5</a> below.</p>
<p><br/></p>
<div class="figure"><span id="fig:ChisquareGoodFitSumMenWomenAcrossUniversity"></span>
<img src="images/CategoricalData/ChisquareGoodFitSumMenWomenAcrossUniversity.png" alt="Setting the jamovi parameters for summing overall numbers of men versus women (admitted plus rejected) across the university for the Cal Berkeley admissions sample data set from @R-base." width="600px" />
<p class="caption">
Figure 5.5: Setting the jamovi parameters for summing overall numbers of men versus women (admitted plus rejected) across the university for the Cal Berkeley admissions sample data set from <span class="citation"><a href="#ref-R-base" role="doc-biblioref">R Core Team</a> (<a href="#ref-R-base" role="doc-biblioref">2021</a>)</span>.
</p>
</div>
<p><br/></p>
<p>You should see the following results when you do this. Note that these are the numbers that we provided above for men and women across the six largest graduate-school programs at the university.</p>
<p><br/></p>
<pre><code>## 
##  DESCRIPTIVES
## 
##  Descriptives              
##  ───────────────────────── 
##           Gender    Freq   
##  ───────────────────────── 
##    Sum    Female    1835   
##           Male      2691   
##  ─────────────────────────</code></pre>
<p><br/></p>
<p>With these numbers, you will need to write down the relative percentages of men vs. women in the data set. Thus, percentage of men applicants overall (across departments) is as follows:</p>
<p><br/></p>
<p><span class="math display">\[\%\;males_{overall}=\frac{2691}{2691+1835} = \frac{2691}{4526}=.5945=59.45\%\]</span></p>
<p><br/></p>
<p>And therefore, for women, it’s as follows:</p>
<p><br/></p>
<p><span class="math display">\[\%\;females_{overall}=1-.5945=.4055=40.55\%\]</span></p>
<p><br/></p>
<p>You will need these numbers soon enough.</p>
<p><br/></p>
<p>Now we need to get these figures by academic department (<em>A</em> through <em>F</em>). To do this, we just do the same as in Figure <a href="CategoricalDataAnalysis.html#fig:ChisquareGoodFitSumMenWomenAcrossUniversity">5.5</a> above, but we also slide <em>Dept</em> into the <em>Split by</em> box. See Figure <a href="CategoricalDataAnalysis.html#fig:ChisquareGoodFitSumMenWomenByDepartment">5.6</a> below. In fact, you’ll probably want to get the variables in the <em>Split by</em> box in the order shown in the figure, so you may need to slide <em>Gender</em> out, then slide <em>Dept</em> and then <em>Gender</em> back in a again.</p>
<p><br/></p>
<div class="figure"><span id="fig:ChisquareGoodFitSumMenWomenByDepartment"></span>
<img src="images/CategoricalData/ChisquareGoodFitSumMenWomenByDepartment.png" alt="Setting the jamovi parameters for summing the numbers of men versus women (admitted plus rejected) by academic department at the university for the Cal Berkeley admissions sample data set (UCBAdmissions) from @R-base." width="600px" />
<p class="caption">
Figure 5.6: Setting the jamovi parameters for summing the numbers of men versus women (admitted plus rejected) by academic department at the university for the Cal Berkeley admissions sample data set (UCBAdmissions) from <span class="citation"><a href="#ref-R-base" role="doc-biblioref">R Core Team</a> (<a href="#ref-R-base" role="doc-biblioref">2021</a>)</span>.
</p>
</div>
<p><br/></p>
<p>You should see the numbers below.</p>
<p><br/></p>
<pre><code>## 
##  DESCRIPTIVES
## 
##  Descriptives                      
##  ───────────────────────────────── 
##           Dept    Gender    Freq   
##  ───────────────────────────────── 
##    Sum    A       Female     108   
##                   Male       825   
##           B       Female      25   
##                   Male       560   
##           C       Female     593   
##                   Male       325   
##           D       Female     375   
##                   Male       417   
##           E       Female     393   
##                   Male       191   
##           F       Female     341   
##                   Male       373   
##  ─────────────────────────────────</code></pre>
<p><br/></p>
<p>So now we need to calculate the relative percentages of males versus females applying to each department.</p>
<ul>
<li>Applicants to Department A
<ul>
<li><span class="math inline">\(\%_{males}=\frac{825}{825+108}=\frac{825}{933}=.8842=88.42\%\)</span>; and therefore,</li>
<li><span class="math inline">\(\%_{females}=1-.8842=.1158=11.58\%\)</span></li>
</ul></li>
<li>Applicants to Department B
<ul>
<li><span class="math inline">\(\%_{males}=\frac{560}{560+25}=\frac{560}{585}=.9573=95.73\%\)</span>; and therefore,</li>
<li><span class="math inline">\(\%_{females}=1-.9573=.0427=4.27\%\)</span></li>
</ul></li>
<li>Applicants to Department C
<ul>
<li><span class="math inline">\(\%_{males}=\frac{325}{325+593}=\frac{325}{918}=.3540=35.4\%\)</span>; and therefore,</li>
<li><span class="math inline">\(\%_{females}=1-.3540=.6460=64.6\%\)</span></li>
</ul></li>
<li>Applicants to Department D
<ul>
<li><span class="math inline">\(\%_{males}=\frac{417}{417+375}=\frac{417}{792}=.5265=52.65\%\)</span>; and therefore,</li>
<li><span class="math inline">\(\%_{females}=1-.5265=.4735=47.35\%\)</span></li>
</ul></li>
<li>Applicants to Department E
<ul>
<li><span class="math inline">\(\%_{males}=\frac{191}{191+393}=\frac{191}{584}=.3271=32.71\%\)</span>; and therefore,</li>
<li><span class="math inline">\(\%_{females}=1-.3271=.6729=67.29\%\)</span></li>
</ul></li>
<li>Applicants to Department F:
<ul>
<li><span class="math inline">\(\%_{males}=\frac{373}{373+341}=\frac{373}{724}=.5152=51.52\%\)</span>; and therefore,</li>
<li><span class="math inline">\(\%_{females}=1-.5152=.4848=48.48\%\)</span></li>
</ul></li>
</ul>
<p><br/></p>
<p>We are done with calculating relative proportions of applicants by gender. Now we need to create some filters.</p>
<p><br/></p>
</div>
<div id="UCBAdmissionsFiltering" class="section level5" number="5.1.2.2.2">
<h5><span class="header-section-number">5.1.2.2.2</span> Filtering</h5>
<p>Due to a quirk in jamovi, in the sole case of chi-square goodness-of-fit tests, it was most convenient to save 7 different jamovi (.omv) files. We did this after we created each filter (See section <a href="BasicDataOperations.html#FilteringData">2.5.2</a> for how to filter data).</p>
<p>In the first filter, we wanted to filter <strong>in</strong> all the rows that say <em>Admitted</em> under <em>Admit</em>, and filter <strong>out</strong> all the rows that have <em>Rejected</em> under <em>Admit</em>. We left the variable <em>Dept</em> alone for the first filter. This filter gave us the counts for men and women who were <em>admitted</em> to the six largest graduate schools at Cal.</p>
<p>This was easy to do. We just typed the following into the filter function:</p>
<blockquote>
<p>=Admit==‘Admitted’</p>
</blockquote>
<p><br/></p>
<p>(you saw this kind of formula before in Section <a href="BasicDataOperations.html#FilteringData">2.5.2</a>).</p>
<p>Your result should look something like Figure <a href="CategoricalDataAnalysis.html#fig:ChisquareGoodFitFilterForAdmittedAcrossUniversity">5.7</a> below.</p>
<p><br/></p>
<div class="figure"><span id="fig:ChisquareGoodFitFilterForAdmittedAcrossUniversity"></span>
<img src="images/CategoricalData/ChisquareGoodFitFilterForAdmittedAcrossUniversity.png" alt="Creating a filter for the UCBAdmissions data set [@R-base] that restricts the rows to the counts that refer to admissions only (no rejections)." width="600px" />
<p class="caption">
Figure 5.7: Creating a filter for the UCBAdmissions data set <span class="citation">(<a href="#ref-R-base" role="doc-biblioref">R Core Team, 2021</a>)</span> that restricts the rows to the counts that refer to admissions only (no rejections).
</p>
</div>
<p><br/></p>
<p>As noted above, there is a strange quirk having to do with the interaction between filters and chi-square goodness-of-fit tests, so we had to save this file as <em>CategoricalData_UCBAdmissions_AllDepartments.omv</em>.</p>
<p>But we needed six more filters, each of which would restrict the analysis to one department (i.e., one of <em>A</em> through <em>F</em>).</p>
<p>To create the first for <em>Department A</em>, we took the <em>CategoricalData_UCBAdmissions_AllDepartments.omv</em> file and saved it as <em>CategoricalData_UCBAdmissions_DepartmentA.omv</em> [<span class="math inline">\((\equiv)\)</span> &gt; <em>Save As</em>].</p>
<p>After doing this, we could modify <em>Filter 1</em> by adding to its conditions. So we re-opened <em>Filter 1</em>, and clicked the <span class="math inline">\(+\)</span> sign on the far, right-hand sign of the line with <span class="math inline">\(f_{x}\)</span>. This creates a second line <span class="math inline">\(f_{x}\)</span> line in addition to the one above it. It is pre-pended by the word <strong>and</strong>. The expression <em>AND</em> is called a <em>conjunction</em> in Boolean logic, and it means “this also must be true.” Ultimately, this means that jamovi will return only the rows where condition 1 (only <em>Admitted"</em>) <strong>AND</strong> condition 2 (only department <em>A</em>) are <strong>both</strong> true. You can see the results of this in Figure <a href="CategoricalDataAnalysis.html#fig:ChisquareGoodFitFilterForAdmittedInDepartmentA">5.8</a> below.</p>
<p><br/></p>
<div class="figure"><span id="fig:ChisquareGoodFitFilterForAdmittedInDepartmentA"></span>
<img src="images/CategoricalData/ChisquareGoodFitFilterForAdmittedInDepartmentA.png" alt="Creating a filter for the UCBAdmissions data set [@R-base] that restricts the rows to the counts that refer to admissions only (no rejections) AND Department A only (filtering out Departments B-F)." width="600px" />
<p class="caption">
Figure 5.8: Creating a filter for the UCBAdmissions data set <span class="citation">(<a href="#ref-R-base" role="doc-biblioref">R Core Team, 2021</a>)</span> that restricts the rows to the counts that refer to admissions only (no rejections) AND Department A only (filtering out Departments B-F).
</p>
</div>
<p><br/></p>
<p>Note that there are two new columns now: <em>Filter 1</em> and <em>F1 (2)</em>. jamovi does this automatically. <em>F1 (2)</em> means that it’s the second part of <em>Filter 1</em>. Also note that all rows are filtered out except for admissions in Department A.</p>
<p>Now we could save this file as another, named <em>CategoricalData_UCBAdmissions_Department.omv</em> (for Department B, obviously). Then, we just changed the second condition to the following:</p>
<blockquote>
<p>and Dept==‘B’</p>
</blockquote>
<p><br/></p>
<p>We needed to repeat this so that we ended up with seven .omv files, each with its own unique filter. Thus:</p>
<p>-CategoricalData_UCBAdmissions_<strong>AllDepartments</strong>.omv<br />
-CategoricalData_UCBAdmissions_Department<strong>A</strong>.omv<br />
-CategoricalData_UCBAdmissions_Department<strong>B</strong>.omv<br />
-CategoricalData_UCBAdmissions_Department<strong>C</strong>.omv<br />
-CategoricalData_UCBAdmissions_Department<strong>D</strong>.omv<br />
-CategoricalData_UCBAdmissions_Department<strong>E</strong>.omv<br />
-CategoricalData_UCBAdmissions_Department<strong>F</strong>.omv</p>
<p><br/></p>
</div>
</div>
<div id="UCBAdmissionsTesting" class="section level4" number="5.1.2.3">
<h4><span class="header-section-number">5.1.2.3</span> Testing</h4>
<p>Now that we had the relative proportions and the necessary filters, we could proceed to the chi-square goodness-of-fit test to determine whether there was actually gender discrimination in graduate admissions at Cal Berkeley in 1973.</p>
<p>First, we wanted to look at the graduate admissions by gender across the university. So we opened the jamovi file CategoricalData_UCBAdmissions_<strong>AllDepartments</strong>.omv. First, to reduce clutter, we clicked the “eye” icon in the filter menu to remove from view all the rows that were filtered out. All that remained visible were admissions. Then we went to the <em>Analyses</em> tab, and selected <em>Frequencies</em> &gt; <em>One Sample Proportion Tests: N Outcomes - <span class="math inline">\(\chi^2\)</span> Goodness of fit</em>. When we opened this, we click-and-dragged to the right the left-hand side of the window headed with <em>Proportion Test (N Outcomes)</em>. This made the data appear on the left (as in Figure <a href="CategoricalDataAnalysis.html#fig:ChisquareGoodFitTestParametersForAllUniversity">5.9</a> below).</p>
<p>We then dragged the <em>Gender</em> variable to the <em>Variable</em> box, and the <em>Freq</em> variable over to the <em>Counts (optional)</em> box.<a href="#fn55" class="footnote-ref" id="fnref55"><sup>55</sup></a></p>
<p>Next, we needed to add in the expected proportions manually. Recall, this is what we did in Section <a href="CategoricalDataAnalysis.html#UCBAdmissionsCalculateRelativeProportions">5.1.2.2.1</a>. The expected proportions will be the same proportions of males versus females in the total applicant pool. The observed values will be the proportions of men versus women that were actually admitted. To the extend that these proportions differ is the extent to which you have evidence of gender discrimination… possibly.</p>
<p>The proportion of male applicants was 59.45%, which we can type in (59.45) to the <em>Expected Proportions</em> box under <em>Male</em>. The complementary proportion for females was 40.55%, so we type in 40.55 under <em>Female</em>. For good measure, we also checked the <em>Expected Counts</em> box.</p>
<p><br/></p>

<div class="rmdnote">
This is actually the reason that you have to create separate files for each goodness-of-fit analysis. The filter applies to <strong>all</strong> analyses. However, each of our analyses requires different values in the <em>Expected Proportions</em> box. Thus, we need to separate the analyses into different files. This is a jamovi quirk that seems only to apply to one-sample tests in jamovi, like the chi-square goodness-of-fit test.
</div>
<p><br/></p>
<p>See Figure <a href="CategoricalDataAnalysis.html#fig:ChisquareGoodFitTestParametersForAllUniversity">5.9</a> below to get an idea of what our settings were.</p>
<p><br/></p>
<div class="figure"><span id="fig:ChisquareGoodFitTestParametersForAllUniversity"></span>
<img src="images/CategoricalData/ChisquareGoodFitTestParametersForAllUniversity.png" alt="jamovi paramaters for a Chi-square goodness-of-fit test on admitted male versus female graduate applicants at UC Berkeley in 1973." width="750px" />
<p class="caption">
Figure 5.9: jamovi paramaters for a Chi-square goodness-of-fit test on admitted male versus female graduate applicants at UC Berkeley in 1973.
</p>
</div>
<p><br/></p>
<p>The results of the chi-square are significant, which you can see below. From this analysis, it looks like males are being preferred in admissions over females. This is because although 712 females were expected to be admitted (under the null hypothesis that there was no discrimination), only 557 were. In contrast, although only 1,043 males were expected to be admitted (if there had been no discrimination), 1,198 were admitted (higher than the expected number). This discrepancy was statistically significant: <span class="math inline">\(\chi^2 (1)=56.5,\;p&lt;.001\)</span>.</p>
<p><br/></p>
<pre><code>## 
##  PROPORTION TEST (N OUTCOMES)
## 
##  Proportions - Gender                              
##  ───────────────────────────────────────────────── 
##    Level                 Count        Proportion   
##  ───────────────────────────────────────────────── 
##    Female    Observed          557     0.3173789   
##              Expected     711.6525     0.4055000   
##                                                    
##    Male      Observed         1198     0.6826211   
##              Expected    1043.3475     0.5945000   
##  ───────────────────────────────────────────────── 
## 
## 
##  χ² Goodness of Fit               
##  ──────────────────────────────── 
##    χ²          df    p            
##  ──────────────────────────────── 
##    56.53196     1    &lt; .0000001   
##  ────────────────────────────────</code></pre>
<p><br/></p>
<p>But we had more detailed information than just overall admissions by gender. We had information by department. This required six different analyses, where we will use the six remaining files that we created since the <em>Expected Proportions</em> values differed for each department (the ones we calculated in section <a href="CategoricalDataAnalysis.html#UCBAdmissionsCalculateRelativeProportions">5.1.2.2.1</a>).</p>
<p>We will not display how to set the parameters in jamovi here. We will simply display the results.</p>
<p><br/></p>
<div id="GoodnessOfFitForDepartmentA" class="section level5" number="5.1.2.3.1">
<h5><span class="header-section-number">5.1.2.3.1</span> Department A</h5>
<p>This file is <em>CategoricalData_UCBAdmissions_DepartmentA.omv</em>. Recall from section <a href="CategoricalDataAnalysis.html#UCBAdmissionsCalculateRelativeProportions">5.1.2.2.1</a> above that the proportion of women applying was 11.58%, whereas the proportion of men applying was 88.42%. The results of the chi-square goodness-of-fit test for Department A are below.</p>
<p><br/></p>
<pre><code>## 
##  PROPORTION TEST (N OUTCOMES)
## 
##  Proportions - Gender                              
##  ───────────────────────────────────────────────── 
##    Level                 Count        Proportion   
##  ───────────────────────────────────────────────── 
##    Female    Observed           89     0.1480865   
##              Expected     69.59580     0.1158000   
##                                                    
##    Male      Observed          512     0.8519135   
##              Expected    531.40420     0.8842000   
##  ───────────────────────────────────────────────── 
## 
## 
##  χ² Goodness of Fit              
##  ─────────────────────────────── 
##    χ²          df    p           
##  ─────────────────────────────── 
##    6.118683     1    0.0133760   
##  ───────────────────────────────</code></pre>
<p><br/></p>
<p>The chi-square goodness-of-fit test for department A was significant: <span class="math inline">\(\chi^2 (1)=6.12,\;p=.013\)</span>. But if you look at observed versus expected values, you’ll see that more females (89) were admitted than expected (70), and fewer males (512) were admitted than expected (531).</p>
<p><br/></p>
</div>
<div id="GoodnessOfFitForDepartmentB" class="section level5" number="5.1.2.3.2">
<h5><span class="header-section-number">5.1.2.3.2</span> Department B</h5>
<p>This file is <em>CategoricalData_UCBAdmissions_DepartmentB.omv</em>. The proportion of women applying was 4.27%, whereas the proportion of men applying was 95.73%. The results of the chi-square goodness-of-fit test for Department B are below.</p>
<p><br/></p>
<pre><code>## 
##  PROPORTION TEST (N OUTCOMES)
## 
##  Proportions - Gender                              
##  ───────────────────────────────────────────────── 
##    Level                 Count        Proportion   
##  ───────────────────────────────────────────────── 
##    Female    Observed           17    0.04594595   
##              Expected     15.79900    0.04270000   
##                                                    
##    Male      Observed          353    0.95405405   
##              Expected    354.20100    0.95730000   
##  ───────────────────────────────────────────────── 
## 
## 
##  χ² Goodness of Fit                
##  ───────────────────────────────── 
##    χ²            df    p           
##  ───────────────────────────────── 
##    0.09536925     1    0.7574591   
##  ─────────────────────────────────</code></pre>
<p><br/></p>
<p>The results of the analysis for Department B were not significant: <span class="math inline">\(\chi^2 (1)=0.0954,\;p=.76\)</span>. Department B seems to have been favoring neither men nor women in their admissions. One more female was admitted (17) than expected (16), and one less male was admitted (353) than expected (354).</p>
<p><br/></p>
</div>
<div id="GoodnessOfFitForDepartmentC" class="section level5" number="5.1.2.3.3">
<h5><span class="header-section-number">5.1.2.3.3</span> Department C</h5>
<p>This file is <em>CategoricalData_UCBAdmissions_DepartmentC.omv</em>. The proportion of women applying was higher this time, at 64.6%. In contrast, the proportion of men applying was down to 35.4%. The results of the chi-square goodness-of-fit test for Department C are below.</p>
<p><br/></p>
<pre><code>## 
##  PROPORTION TEST (N OUTCOMES)
## 
##  Proportions - Gender                             
##  ──────────────────────────────────────────────── 
##    Level                 Count       Proportion   
##  ──────────────────────────────────────────────── 
##    Female    Observed         202     0.6273292   
##              Expected    208.0120     0.6460000   
##                                                   
##    Male      Observed         120     0.3726708   
##              Expected    113.9880     0.3540000   
##  ──────────────────────────────────────────────── 
## 
## 
##  χ² Goodness of Fit               
##  ──────────────────────────────── 
##    χ²           df    p           
##  ──────────────────────────────── 
##    0.4908472     1    0.4835496   
##  ────────────────────────────────</code></pre>
<p><br/></p>
<p>Department C had a similar outcome to Department B. There seems to have been no gender discrimination in their admissions decisions: <span class="math inline">\(\chi^2 (1)=0.491,\;p=.48\)</span>. Six fewer women were accepted (202) than expected (208), and six more men were accepted (120) than expected (114). Not much of a difference.</p>
<p><br/></p>
</div>
<div id="GoodnessOfFitForDepartmentD" class="section level5" number="5.1.2.3.4">
<h5><span class="header-section-number">5.1.2.3.4</span> Department D</h5>
<p>This file is <em>CategoricalData_UCBAdmissions_DepartmentD.omv</em>. The proportion of women applying was roughly even with the men this time, at 47.35%. The proportion of men applying was 52.65%. The results of the chi-square goodness-of-fit test for Department D are below.</p>
<p><br/></p>
<pre><code>## 
##  PROPORTION TEST (N OUTCOMES)
## 
##  Proportions - Gender                             
##  ──────────────────────────────────────────────── 
##    Level                 Count       Proportion   
##  ──────────────────────────────────────────────── 
##    Female    Observed         131     0.4869888   
##              Expected    127.3715     0.4735000   
##                                                   
##    Male      Observed         138     0.5130112   
##              Expected    141.6285     0.5265000   
##  ──────────────────────────────────────────────── 
## 
## 
##  χ² Goodness of Fit               
##  ──────────────────────────────── 
##    χ²           df    p           
##  ──────────────────────────────── 
##    0.1963286     1    0.6577007   
##  ────────────────────────────────</code></pre>
<p><br/></p>
<p>Department D also seems not to have been engaging in any kind of gender discrimination: <span class="math inline">\(\chi^2 (1)=0.196,\;p=.66\)</span>. Four more women were admitted (131) than expected (127), and four fewer men were accepted (138) than expected (142). Again, not much of a difference.</p>
<p><br/></p>
</div>
<div id="GoodnessOfFitForDepartmentE" class="section level5" number="5.1.2.3.5">
<h5><span class="header-section-number">5.1.2.3.5</span> Department E</h5>
<p>This file is <em>CategoricalData_UCBAdmissions_DepartmentE.omv</em>. The proportion of women applying was higher again, at 67.29% of applicants. The proportion of men applying was down to 32.71% for this department. The results of the chi-square goodness-of-fit test for Department E are below.</p>
<p><br/></p>
<pre><code>## 
##  PROPORTION TEST (N OUTCOMES)
## 
##  Proportions - Gender                             
##  ──────────────────────────────────────────────── 
##    Level                 Count       Proportion   
##  ──────────────────────────────────────────────── 
##    Female    Observed          94     0.6394558   
##              Expected    98.91630     0.6729000   
##                                                   
##    Male      Observed          53     0.3605442   
##              Expected    48.08370     0.3271000   
##  ──────────────────────────────────────────────── 
## 
## 
##  χ² Goodness of Fit               
##  ──────────────────────────────── 
##    χ²           df    p           
##  ──────────────────────────────── 
##    0.7470133     1    0.3874235   
##  ────────────────────────────────</code></pre>
<p><br/></p>
<p>Department E as well, seems not to have engaged in gender discrimination: <span class="math inline">\(\chi^2 (1)=0.747,\;p=.39\)</span>. Five more men were accepted (53) than expected (48), and five fewer women were accepted (94) than expected (99).</p>
<p><br/></p>
</div>
<div id="GoodnessOfFitForDepartmentF" class="section level5" number="5.1.2.3.6">
<h5><span class="header-section-number">5.1.2.3.6</span> Department F</h5>
<p>This file is <em>CategoricalData_UCBAdmissions_DepartmentF.omv</em>. The proportion of women applying to this department was about even with the men again, at 48.48%. The proportion of men applying was about equal at 51.52%. The results of the chi-square goodness-of-fit test for Department F are below.</p>
<p><br/></p>
<pre><code>## 
##  PROPORTION TEST (N OUTCOMES)
## 
##  Proportions - Gender                             
##  ──────────────────────────────────────────────── 
##    Level                 Count       Proportion   
##  ──────────────────────────────────────────────── 
##    Female    Observed          24     0.5217391   
##              Expected    22.30080     0.4848000   
##                                                   
##    Male      Observed          22     0.4782609   
##              Expected    23.69920     0.5152000   
##  ──────────────────────────────────────────────── 
## 
## 
##  χ² Goodness of Fit               
##  ──────────────────────────────── 
##    χ²           df    p           
##  ──────────────────────────────── 
##    0.2513001     1    0.6161611   
##  ────────────────────────────────</code></pre>
<p><br/></p>
<p>And finally, the same is true of Department F: no apparent gender discrimination with <span class="math inline">\(\chi^2 (1)=0.251,\;p=.62\)</span>. Two more females were accepted (24) than expected (22), in contrast with the males, where two fewer were accepted (22) than expected (24).</p>
<p><br/></p>
</div>
</div>
<div id="GoodnessOfFitReporting" class="section level4" number="5.1.2.4">
<h4><span class="header-section-number">5.1.2.4</span> Reporting</h4>
<p>See <em>Appendix A</em> for a review of how to report statistics in APA format.</p>
<p>One could report the null findings from the first pair of randomly generated variables in the following way:</p>
<blockquote>
<p>At first blush, it looked as if there had been gender discrimination in the the graduate-admissions process at the University of California - Berkeley in 1973. Indeed, when we applied a chi-square goodness-of-fit test to the counts of male vs. female admissions across the six largest departments (against the respective numbers that applied), we obtained significance, <span class="math inline">\(\chi^2 (1)=56.5,\;p&lt;.001\)</span>. Men were being admitted at a rate about 10% higher than expected, whereas women were being admitted at a rate about 10% lower than expected. However, when we analyzed the admissions rate by department (the six largest departments only), we found that only one of these departments showed a significant discrepancy between the expected and actual admission rates between the sexes. This was department A, <span class="math inline">\(\chi^2 (1)=6.12,\;p=.013\)</span>; all other <em>p</em>s &gt; .38. Surprisingly however, it was also clear that females were being favored over males in department A.</p>
</blockquote>
<p><br/></p>
</div>
<div id="GoodnessOfFitConclusion" class="section level4" number="5.1.2.5">
<h4><span class="header-section-number">5.1.2.5</span> Conclusion</h4>
<p>In addition to providing some insight in how to do a chi-square goodness-of-fit test, it is actually also a famous case of <em>Simpson’s Paradox</em> (in fact, it is listed in the <a href="https://en.wikipedia.org/wiki/Simpson%27s_paradox">Wikipedia entry</a> for the term). This is a phenomenon where an apparent pattern at one level gets cancelled out or even reverses itself at another level. In the 1973 graduate-school admissions data at UC Berkeley, they found evidence for preference for men if they looked at all graduate schools together, but found a small bias for women when they analyzed the data by department.</p>
<p>Apparently, large numbers of men had been applying to schools with high admission rates (low competition), as long as they met minimal requirements, whereas women had been applying in larger numbers to departments that had lower admission rates, even among qualified candidates (high competition). This resulted in what looked to be, on aggregate, a bias for men being accepted to graduate school compared to women, but was really only the result of lots of men getting into less competitive programs.</p>
<p>These data were originally reported by <span class="citation"><a href="#ref-BickelHammelOconnell1975" role="doc-biblioref">Bickel, Hammel, &amp; O’Connell</a> (<a href="#ref-BickelHammelOconnell1975" role="doc-biblioref">1975</a>)</span>. A link to this reference (only) can be found at the <em>Science</em> website <a href="https://science.sciencemag.org/content/187/4175/398">here</a>. But if you are a student at Texas A&amp;M, you can obtain the article <a href="https://www-jstor-org.srv-proxy1.library.tamu.edu/stable/1739581">here</a>.</p>
<p><br/></p>
</div>
</div>
</div>
<div id="ChiSquareTestOfIndependence" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Chi-square test of independence</h2>
<p>This test looks at whether the counts across two variables are random or whether the variables are <em>contingent</em>. For instance, are coffee drinkers just as likely to be larks (“morning people”) as non-coffee drinkers? Are left-handers just as likely to be diagnosed with dyslexia as right-handers?</p>
<p>The key difference between this test and the goodness-of-fit test, is that this one looks for balance across two variables (as established by overall group size), whereas the goodness-of-fit test involved only one variable tested against known proportions.</p>
<p><br/></p>
<div id="ChiSquareTestOfIndependenceChapek9" class="section level3" number="5.2.1">
<h3><span class="header-section-number">5.2.1</span> Basic: The <em>Chapek 9</em> data</h3>
<p>The <em>Chapek 9</em> data from <span class="citation"><a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft</a> (<a href="#ref-lsj" role="doc-biblioref">2019, sec. 10.2</a>)</span> is from the imagination of the primary author of that book. But it is a good one for illustration. You can obtain the data set from jamovi by clicking <span class="math inline">\((\equiv)\)</span> &gt; <em>Open</em> &gt; <em>Data library</em> &gt; <em>learning statistics with jamovi</em> &gt; <em>Chapek 9</em>.</p>
<p>The story goes that the residents of Chapek 9 (a city) are all robots, and to gain access, you must be a robot. So the robots design a test to determine if someone is a robot or a human.<a href="#fn56" class="footnote-ref" id="fnref56"><sup>56</sup></a> The test that the robots devised asked w(whether a candidate to enter the city preferred puppies, flowers, or large, properly formatted data files. But the validity of the test needed to be checked against data that were collected (in someone’s imagination).</p>
<p><br/></p>
<div id="ChiSquareTestOfAssociationBasicChapek9Inspecting" class="section level4" number="5.2.1.1">
<h4><span class="header-section-number">5.2.1.1</span> Inspecting</h4>
<p>The first thing to do is create a cross-tabulation of the data. Go to the Analyses tab and click <em>Frequencies</em> &gt; <em>Contingency Tables</em> &gt; <em>Independent Samples <span class="math inline">\(\chi^2\)</span> test of association</em>. <em>species</em> should go in the <em>Columns</em> box, and <em>choice</em> should go in the <em>Rows</em> box.<a href="#fn57" class="footnote-ref" id="fnref57"><sup>57</sup></a> The parameters you need to choose to follow <span class="citation"><a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft</a> (<a href="#ref-lsj" role="doc-biblioref">2019</a>)</span> are as depicted in Figure <a href="CategoricalDataAnalysis.html#fig:ChisquareTestOfIndependenceChapek9Parameters">5.10</a> below.</p>
<p><br/></p>
<div class="figure"><span id="fig:ChisquareTestOfIndependenceChapek9Parameters"></span>
<img src="images/CategoricalData/ChisquareTestOfIndependenceChapek9Parameters.png" alt="Parameter settings in jamovi for a chi-square test of independenc on the Chapek 9 data in @lsj." width="600px" />
<p class="caption">
Figure 5.10: Parameter settings in jamovi for a chi-square test of independenc on the Chapek 9 data in <span class="citation"><a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft</a> (<a href="#ref-lsj" role="doc-biblioref">2019</a>)</span>.
</p>
</div>
<p><br/></p>
<p>The result should look like the following:</p>
<p><br/></p>
<pre><code>## 
##  CONTINGENCY TABLES
## 
##  Contingency Tables                                          
##  ─────────────────────────────────────────────────────────── 
##    choice                robot       human       Total       
##  ─────────────────────────────────────────────────────────── 
##    puppy     Observed          13          15           28   
##              Expected    13.53333    14.46667     28.00000   
##                                                              
##    flower    Observed          30          13           43   
##              Expected    20.78333    22.21667     43.00000   
##                                                              
##    data      Observed          44          65          109   
##              Expected    52.68333    56.31667    109.00000   
##                                                              
##    Total     Observed          87          93          180   
##              Expected    87.00000    93.00000    180.00000   
##  ─────────────────────────────────────────────────────────── 
## 
## 
##  χ² Tests                                                    
##  ─────────────────────────────────────────────────────────── 
##                                Value       df    p           
##  ─────────────────────────────────────────────────────────── 
##    χ²                          10.72157     2    0.0046972   
##    χ² continuity correction    10.72157     2    0.0046972   
##    N                                180                      
##  ─────────────────────────────────────────────────────────── 
## 
## 
##  Nominal                          
##  ──────────────────────────────── 
##                       Value       
##  ──────────────────────────────── 
##    Phi-coefficient          NaN   
##    Cramer&#39;s V         0.2440580   
##  ────────────────────────────────</code></pre>
<p><br/></p>
<p>For good measure, we also included a barplot with <em>species</em> as a <em>Split by</em> variable in the <em>Descriptives</em> menu (see section <a href="CategoricalDataAnalysis.html#ChiSquareGoodnessOfFitBasicCardsInspecting">5.1.1.1</a> above for the right parameter settings). You just additionally slide <em>species</em> into the <em>Split by</em> column.</p>
<p><br/></p>
<pre><code>## 
##  DESCRIPTIVES</code></pre>
<p><img src="ElemStatsLabManual_files/figure-html/unnamed-chunk-91-1.svg" width="672" /></p>
<p><br/></p>
<p>In the data set you can see that there were 180 participants, 87 who turned out to be robots (in reality), and 93 who turned out to be human. The main question is whether the responses to <em>flower</em>, <em>puppy</em>, and <em>large, properly formatted data file</em> were equally proportioned across both humans and robots. If so, the test is no good at distinguishing them. But if not, then it might have some value as a shibboleth.</p>
<p>The expected values are calculated by dividing the total number of participants (human and robot) who chose, say, <em>puppy</em>, and dividing by the total (180, then applying that ratio to the population of each group. There were 28 participants who chose <em>puppy</em>, which comprises <span class="math inline">\(\frac {28}{180}=15.55\%\)</span> So the expected value for humans was <span class="math inline">\(Expected_{human}=93 \times.1555=14.5\)</span>. For robots, this was <span class="math inline">\(Expected_{robot}=87 \times.1555=13.5\)</span>. The same is done for the other two categories (<em>flowers</em> and <em>data files</em>). These are then compared to the observed values for each group through the formula for the chi-square test for independence, which we will get to shortly.</p>
<p><br/></p>
</div>
<div id="ChiSquareTestOfAssociationBasicChapek9Hypothesizing" class="section level4" number="5.2.1.2">
<h4><span class="header-section-number">5.2.1.2</span> Hypothesizing</h4>
<p>The null hypothesis in this case is that the proportion of preferences for each object across species is the same. Or <span class="math inline">\(H_0\)</span>:</p>
<p><span class="math inline">\(P_{human_{puppy}}=P_{robot_{puppy}}\)</span><br />
<span class="math inline">\(P_{human_{flower}}=P_{robot_{flower}}\)</span><br />
<span class="math inline">\(P_{human_{ProperlyFormattedDataFile}}=P_{robot_{ProperlyFormattedDataFile}}\)</span></p>
<p><br/></p>
<p>The research hypothesis would be that any one or more of those equivalencies is false.</p>
<p><br/></p>
</div>
<div id="ChiSquareTestOfAssociationBasicChapek9Testing" class="section level4" number="5.2.1.3">
<h4><span class="header-section-number">5.2.1.3</span> Testing</h4>
<p>The formula for this test is in <span class="citation"><a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft</a> (<a href="#ref-lsj" role="doc-biblioref">2019, sec. 10.2.1</a>, p. 227)</span>, and is as follows:</p>
<p><span class="math display">\[\chi^2=\sum_{i=1}^{r} \sum_{j=1}^{c} \frac{(O_{ij}-E_{ij})^2}{E_{ij}}\]</span></p>
<p><br/></p>

<div class="rmdnote">
<p><strong>NOTE</strong>: The double sigmas <span class="math inline">\(\sum_{i=1}^{r} \sum_{j=1}^{c}\)</span> are not as scary as they look. Just replace <em>r</em> with <em>rows</em> (object preferences) and and <em>c</em> with columns (species) and you will see that these are just the combinations of object preferences by species. That is, <em>i</em> takes the values <em>puppy</em>, <em>flower</em>, and <em>large, properly formatted data file</em>, whereas <em>j</em> takes on the values <em>human</em> and <em>robot</em>.</p>
Walking through this might help. You start with <span class="math inline">\(i=robot\)</span> on the left-hand sigma, then choose <span class="math inline">\(j=puppy\)</span> in the right-hand sigma. With those two values for <em>i</em> and <em>j</em> (i.e., <em>robots who chose puppies</em>), you can calculate the formula on the right. After you do that, you keep the sigma on the left constant (i.e., <span class="math inline">\(i=robot\)</span>) and change the sigma on the right by one to <em>flower</em> (i.e., <em>robots who chose flowers</em>, or <span class="math inline">\(j=flower\)</span>). Then you plug the appropriate numbers into the formula again to get another number. That gets added to the last one you calculater. Then you do <em>large, properly formated data files</em>. When you have exhasted all the values of <em>j</em> for <em>robots</em>, you then change the sigma on the left to refer to <em>humans</em> (i.e., <span class="math inline">\(i=human\)</span>). Then you start all over again for the different values of <em>j</em>. When you have exhausted all the values for <em>j</em> on every vaue of <em>i</em>, you are done.
</div>
<p><br/></p>
<p>Plugging in the <em>Expected</em> and <em>Observed</em> values into the formula renders the <em>obtained value</em>. The degrees of freedom are determined by the total number of data points minus the number of constraints. In this case, it’s <span class="math inline">\((r-1)(c-1)=(3-1)(2-1)=(2)(1)=2\)</span>. See <span class="citation"><a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft</a> (<a href="#ref-lsj" role="doc-biblioref">2019, sec. 10.2.1</a>, pp. 227-228)</span> for more detail.</p>
<p>The degrees of freedom define the particular chi-square distribution that the obtained value gets evaluated against.</p>
<p><br/></p>
<p><img src="ElemStatsLabManual_files/figure-html/unnamed-chunk-93-1.svg" width="672" /></p>
<p><br/></p>
<p>Obviously, this chi-square distribution looks very different from the one above with 3 degrees of freedom (with the cards data). The chi-square distribution in general has the unique feature of changing its shape dramatically depending on the degrees of freedom, something that doesn’t change very much with <em>t</em>-distributions (next chapter).</p>
<p>But nothing changes with respect to its function. It defines the probabilities of an infinite set of test outcomes (from an infinite set of study replications) with 2 degrees of freedom, all under the assumption that the null hypothesis is true. With 2 degrees of freedom, you can see that the most common obtained value under the null hypothesis would be 0, with progressively diminishing probabilities for more extreme obtained values. Moreover, the critical value on this distribution (for <span class="math inline">\(\alpha=.05\)</span>) is 5.991. This means that obtained values of 5.991 or greater are less than 5% likely to occur if the null hypothesis is true.</p>
<p>The chi-square test statistic came out as follows: <span class="math inline">\(\chi^2 (2)=10.7,p=.005\)</span>. Thus, our obtained value was quite improbably if the null hypothesis were true. As a result, we have enough confidence to reject the null hypothesis and resort to the research hypothesis.</p>
<p>Without going in to too much detail, it is pretty clear from the test results, the table, and the figure that the robots were over-choosing <em>flower</em> and the humans were over-choosing <em>large, properly formatted data files</em>.</p>
<p>This effect was not that strong as Cramér’s <em>V</em> was only .244. According to <span class="citation"><a href="#ref-Cohen1988" role="doc-biblioref">Cohen</a> (<a href="#ref-Cohen1988" role="doc-biblioref">1988</a>)</span>, who was the great grandfather of effect sizes, this would be a small-ish effect size.</p>
<p><br/></p>
</div>
<div id="ChiSquareTestOfAssociationBasicChapek9Reporting" class="section level4" number="5.2.1.4">
<h4><span class="header-section-number">5.2.1.4</span> Reporting</h4>
<p>Borrowing from Danielle Navarro’s imagination here a little bit, this is how we could write this up:</p>
<blockquote>
<p>We carried out a chi-square test of independence on the <em>Chapek 9</em> data set. The results were significant, <span class="math inline">\(\chi^2 (2)=10.7,p=.005\)</span>. There were roughly as many robots (87) as humans (93) who responded. Responses to <em>puppy</em> looked to be about equally likely across the two groups. However, humans responded with a disproportionate number of preferences for <em>large, properly formatted data files</em> compared to robots, whereas the robots seemed to respond with a disproportionate number of preferences for <em>flower</em>. It turns out that the robots had a policy to murder humans who answered honestly and identified themselves as human with a <em>puppy</em> or <em>flower</em> response. Many of the humans had caught on to this policy, and therefore chose <em>file</em> out of concern for their safety. The unusual number of robot preferences for <em>flower</em> is harder to explain, but is partly due to the fact that humans were avoiding that choice out of fear for their lives.</p>
</blockquote>
<p><br/></p>
</div>
</div>
<div id="NarcissisticPersonalityInventory" class="section level3" number="5.2.2">
<h3><span class="header-section-number">5.2.2</span> Advanced: The Narcissistic Personality Inventory</h3>
<p>We will use the for-fun, online version of the Narcissistic Personality Inventory (NPI) to illustrate how to perform more realistic version of this test in jamovi. This data is part of the <em>Dark Triad</em>. You can take the dark-triad survey yourself for fun <a href="https://openpsychometrics.org/tests/SD3/">here</a>.</p>
<p><br/></p>

<div class="rmdnote">
<strong>NOTE</strong>: The data in the survey we linked you to, as well as the data we analyze below, are being collected “for fun.” You should not take any results be obtained very seriously. A more serious analysis of the NPI portion was reported by <span class="citation"><a href="#ref-RaskinTerry1988" role="doc-biblioref">Raskin &amp; Terry</a> (<a href="#ref-RaskinTerry1988" role="doc-biblioref">1988</a>)</span>, located online <a href="http://proxy.library.tamu.edu.srv-proxy1.library.tamu.edu/login?url=http://search.ebscohost.com/login.aspx?direct=true&amp;db=pdh&amp;AN=1988-25254-001&amp;site=ehost-live">here</a> for Texas A&amp;M students.
</div>
<p><br/></p>
<div id="NarcissisticPersonalityInventoryObtainingData" class="section level4" number="5.2.2.1">
<h4><span class="header-section-number">5.2.2.1</span> Obtaining the data</h4>
<p>The data and the codebook are available both available online <a href="http://openpsychometrics.org/_rawdata/">here</a>. You need to scroll down to the row with <em>Narcissistic Personality Inventory</em> and click the link on the far right-hand side labeled <em>NPI</em>. This will download a .zip file with the files you need. Students in PSYC 301 at Texas A&amp;M can access these files in eCampus under <em>Lab: Lab manual data sets</em> &gt; <em>CategoricalData_NPI</em>.</p>
<p><br/></p>

<div class="rmdnote">
<strong>NOTE</strong>: This data set is fairly large currently, with over 11,000 observations. Therefore, we will not display the table in this lab manual
</div>
<p><br/></p>
</div>
<div id="NarcissisticPersonalityInventoryPreparing" class="section level4" number="5.2.2.2">
<h4><span class="header-section-number">5.2.2.2</span> Preparing</h4>
<p>One could analyze a combination of almost any of two of the variables <em>Q1</em> through <em>Q40</em>. The variables don’t have names other than <em>Q##</em>. Respondents simply choose one of two answers that appear on the screen. We arbitrarily chose the following questions to analyze in chi-square test of independence: <em>Q16</em> and <em>Q24</em>. These two questions carried the following two response possibilities according to the codebook (i.e., <em>codebook.txt</em>):</p>
<ul>
<li>Q16
<ul>
<li>1 = I can read people like a book</li>
<li>2 = People are sometimes hard to understand</li>
</ul></li>
<li>Q24
<ul>
<li>1 = I expect a great deal from other people</li>
<li>2 = I like to do things for other people</li>
</ul></li>
</ul>
<p><br/></p>
<p>Thus, presumably, such an analysis would look at whether one’s self-assessed ability to understand others’ behavior (theory of mind) predicts how self-centered one is. Because… why not?</p>
<p>The first step was to re-code <em>Q16</em> according to the codebook (as above). We clicked the <em>Data</em> tab and double-clicked variable <em>Q16</em>. We typed “Theory of Mind” into the <em>Description</em> box, and then typed over “1” with <em>I can read people like a book</em> and “2” with <em>People are sometimes hard to understand</em>. Then we decided, in order to reduce the width of the contingency table, to replace these rather long labels with the shorter versions: <em>Good Theory of Mind</em> and <em>Poor Theory of Mind</em>, respectively. Finally, we made sure that the <em>Data type</em> drop-down menu was set to <em>text</em>. These settings are illustrated below in Figure <a href="CategoricalDataAnalysis.html#fig:ChisquareTestOfIndependenceQ16Settings">5.11</a>.</p>
<p><br/></p>
<div class="figure"><span id="fig:ChisquareTestOfIndependenceQ16Settings"></span>
<img src="images/CategoricalData/ChisquareTestOfIndependenceQ16Settings.png" alt="Settings in jamovi for the variable Q16 from the online version of the Narcisisstic Personality Inventory from @RaskinTerry1988." width="600px" />
<p class="caption">
Figure 5.11: Settings in jamovi for the variable Q16 from the online version of the Narcisisstic Personality Inventory from <span class="citation"><a href="#ref-RaskinTerry1988" role="doc-biblioref">Raskin &amp; Terry</a> (<a href="#ref-RaskinTerry1988" role="doc-biblioref">1988</a>)</span>.
</p>
</div>
<p><br/></p>
<p>Figure <a href="CategoricalDataAnalysis.html#fig:ChisquareTestOfIndependenceQ24Settings">5.12</a> below shows how to do the same thing for <em>Q24</em> (replacing <em>I expect a great deal from other people</em> with <em>Self-centered</em>, and <em>I like to do things for other people</em> with <em>Selfless</em>.</p>
<p><br/></p>
<div class="figure"><span id="fig:ChisquareTestOfIndependenceQ24Settings"></span>
<img src="images/CategoricalData/ChisquareTestOfIndependenceQ24Settings.png" alt="Settings in jamovi for the variable Q24 from the online version of the NPI from @RaskinTerry1988." width="600px" />
<p class="caption">
Figure 5.12: Settings in jamovi for the variable Q24 from the online version of the NPI from <span class="citation"><a href="#ref-RaskinTerry1988" role="doc-biblioref">Raskin &amp; Terry</a> (<a href="#ref-RaskinTerry1988" role="doc-biblioref">1988</a>)</span>.
</p>
</div>
<p><br/></p>
</div>
<div id="NarcissisticPersonalityInventoryHypothesizing" class="section level4" number="5.2.2.3">
<h4><span class="header-section-number">5.2.2.3</span> Hypothesizing</h4>
<p>The null hypothesis in this case is that the proportion of those with a self-assessed good theory of mind are distributed equally across those who are relatively self-centered vs. those who are not. Or <span class="math inline">\(H_0\)</span>:</p>
<p><span class="math inline">\(P_{good.theory.of.mind_{self-centered}}=P_{bad.theory.of.mind_{self-centered}}\)</span><br />
<span class="math inline">\(P_{good.theory.of.mind_{selfless}}=P_{bad.theory.of.mind_{selfless}}\)</span></p>
<p><br/></p>
<p>… or alternatively:</p>
<p><span class="math inline">\(P_{self-centered_{good.theory.of.mind}}=P_{selfless_{good.theory.of.mind}}\)</span><br />
<span class="math inline">\(P_{self-centered_{bad.theory.of.mind}}=P_{selfless_{bad.theory.of.mind}}\)</span></p>
<p><br/></p>
<p>The research hypothesis would be that any one or more of those equivalencies is false.</p>
<p>This is all we needed for an analysis.</p>
<p><br/></p>
</div>
<div id="NarcissisticPersonalityInventoryTesting" class="section level4" number="5.2.2.4">
<h4><span class="header-section-number">5.2.2.4</span> Testing</h4>
<p>First, we reported some descriptive statistics for the survey. We wanted the counts for <em>Q24</em> (“Selflessness”) split by the levels of <em>Q16</em> (“Theory of Mind”). This would give us a birds-eye view of the responses out of 11,186 (as of the writing of this lab manual). See section <a href="DescriptiveStats.html#Frequencies">3.2.3</a> for instructions on how to do this yourself.</p>
<p><br/></p>
<pre><code>## 
##  DESCRIPTIVES
## 
##  Descriptives                               
##  ────────────────────────────────────────── 
##               Q16                    Q24    
##  ────────────────────────────────────────── 
##    N          Poor Theory of Mind    6174   
##               Good Theory of Mind    5012   
##    Missing    Poor Theory of Mind      19   
##               Good Theory of Mind      17   
##  ──────────────────────────────────────────</code></pre>
<p><img src="ElemStatsLabManual_files/figure-html/unnamed-chunk-97-1.svg" width="672" /></p>
<p><br/></p>
<p>Thus, of the 11,186 responses, about 55% reported having a relatively poor theory of mind (6,174), and about 45% (5,012) reported having a relative good theory of mind. Less than half of one percent failed to provide any response, equally distributed across both levels of Theory of Mind. A cursory glance at the bar plot suggests that those reporting a relatively poor theory of mind are more likely to self-report selflessness than those reporting a relatively good theory of mind. But plots can deceive. We needed to carry out an inferential test to see if this might be a real difference or not.</p>
<p>Carrying this procedure out was much more straightforward than the chi-square goodness-of-fit test in the last section. We started by clicking the <em>Analyses</em> tab, and then <em>Frequencies</em>. Drag <em>Q16</em> to the <em>Rows</em> box and <em>Q24</em> to the <em>Columns</em> box (or vice-versa; it doesn’t matter).</p>
<p>Also click the following options.</p>
<ul>
<li>Statistics:
<ul>
<li>Tests
-<span class="math inline">\(\chi^2\)</span></li>
<li>Nominal
<ul>
<li>Phi and Cramér’s V</li>
</ul></li>
</ul></li>
<li>Cells:
<ul>
<li>Counts
<ul>
<li>Observed counts</li>
<li>Expected counts</li>
</ul></li>
<li>Percentages
<ul>
<li>Row</li>
<li>Column</li>
</ul></li>
</ul></li>
</ul>
<p><br/></p>
<p>See Figure <a href="CategoricalDataAnalysis.html#fig:ChisquareTestOfIndependenceParameters">5.13</a> for a visual illustration of this.</p>
<p><br/></p>
<div class="figure"><span id="fig:ChisquareTestOfIndependenceParameters"></span>
<img src="images/CategoricalData/ChisquareTestOfIndependenceParameters.png" alt="Parameter settings in jamovi for a chi-square test of independence on the online NPI data, originally from @RaskinTerry1988." width="600px" />
<p class="caption">
Figure 5.13: Parameter settings in jamovi for a chi-square test of independence on the online NPI data, originally from <span class="citation"><a href="#ref-RaskinTerry1988" role="doc-biblioref">Raskin &amp; Terry</a> (<a href="#ref-RaskinTerry1988" role="doc-biblioref">1988</a>)</span>.
</p>
</div>
<p><br/></p>
<p>Choosing these options gave us the following output:</p>
<p><br/></p>
<pre><code>## 
##  CONTINGENCY TABLES
## 
##  Contingency Tables                                                                    
##  ───────────────────────────────────────────────────────────────────────────────────── 
##    Q16                                       Selfless     Self-centered    Total       
##  ───────────────────────────────────────────────────────────────────────────────────── 
##    Poor Theory of Mind    Observed                4521             1653         6174   
##                           Expected            4278.638         1895.362     6174.000   
##                           % within row        73.22643         26.77357    100.00000   
##                           % within column     58.32043         48.13628     55.19399   
##                                                                                        
##    Good Theory of Mind    Observed                3231             1781         5012   
##                           Expected            3473.362         1538.638     5012.000   
##                           % within row        64.46528         35.53472    100.00000   
##                           % within column     41.67957         51.86372     44.80601   
##                                                                                        
##    Total                  Observed                7752             3434        11186   
##                           Expected            7752.000         3434.000    11186.000   
##                           % within row        69.30091         30.69909    100.00000   
##                           % within column    100.00000        100.00000    100.00000   
##  ───────────────────────────────────────────────────────────────────────────────────── 
## 
## 
##  χ² Tests                               
##  ────────────────────────────────────── 
##          Value       df    p            
##  ────────────────────────────────────── 
##    χ²    99.80693     1    &lt; .0000001   
##    N        11186                       
##  ────────────────────────────────────── 
## 
## 
##  Nominal                           
##  ───────────────────────────────── 
##                       Value        
##  ───────────────────────────────── 
##    Phi-coefficient    0.09445891   
##    Cramer&#39;s V         0.09445891   
##  ─────────────────────────────────</code></pre>
<p><br/></p>
</div>
<div id="NarcissisticPersonalityInventoryInterpreting" class="section level4" number="5.2.2.5">
<h4><span class="header-section-number">5.2.2.5</span> Interpreting</h4>
<p>The results were “highly” significant, with <span class="math inline">\(\chi^2 (1)=99.8,p&lt;.001\)</span>. We could tentatively conclude that having a good or poor theory of mind does affect your selflessness. Those with poor theories of mind showed higher counts of selflessness (4,521) than expected (4,279), whereas those with good theories of mind showed unexpectedly lower counts of selflessness (3,231) than expected (3,473). The converse was true of the counts of <em>Self-centered</em>. However, the significance may have been primarily an artifact of having such a large sample size (11,186). The effect-size measures (the <span class="math inline">\(\phi\)</span> coefficient and <em>Cramér’s V</em>) were both quite small at .095.</p>
<p><br/></p>
</div>
<div id="NarcissisticPersonalityInventoryReporting" class="section level4" number="5.2.2.6">
<h4><span class="header-section-number">5.2.2.6</span> Reporting</h4>
<p>This is how it might have been written up:</p>
<blockquote>
<p>We took variables <em>Q16</em> (“Theory of Mind”: <em>Good</em> vs. <em>Poor</em>) and <em>Q24</em> (“Selflessness”: <em>Selfless</em> vs. <em>Self-centered</em>) and subjected the relative counts of these levels to a <span class="math inline">\(\chi^2\)</span> test of independence. All else being equal, the null hypothesis would predict that 69.3% of the respondents for both good and poor theories of mind would have reported that they were selfless, and 30.7% would have reported that they were self-centered. The results were significant [<span class="math inline">\(\chi^2 (1)=99.8,p&lt;.001\)</span>] with those who self-reported a poor theory of mind also reporting unexpectedly higher counts of selflessness (4,521, or 73.2%) than 69.3% would predict (4,279), and those who self-reported a good theory of mind also reporting unexpectedly lower counts of selflessness (3,231, or 64.5%) than 69.3% would predict (3,473). The effect size was negligible, however, with <span class="math inline">\(\phi=.095\)</span>. Thus, the statistical significance could be an artifact of the large sample (N= 11,186).</p>
</blockquote>
<p><br/></p>
<p>Incidentally, this is a good example of how a bar plot (see above) can deceive the statistically naïve. The difference in the heights of the bars was probably due mostly to the fact that there were more people overall who self-reported as having a relatively poor theory of mind (6,174 versus 5,012).</p>
<p>It’s also an example of how a large sample size can exaggerate the inferential statistics by inflating obtained values (and thereby deflating <em>p</em>-values). Results should only be interpreted in conjunction with an effect size (since effect sizes are designed to temper the interpretation of test statistics by being immune to sample sizes).</p>
<p><br/></p>
</div>
</div>
</div>
<div id="OutsideHelpOnChisquare" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> Outside help on chi-square</h2>
<p>For whatever reason, there is less overall outside help on analyzing frequency data in jamovi.</p>
<p>Still, to reinforce your learning here, you can go to <a href="https://datalab.cc/tools/jamovi">datalab.cc</a> <span class="citation">(<a href="#ref-datalab.cc" role="doc-biblioref">Poulson, 2019</a>)</span>. The first video to watch is #45, which discusses analyzing count data in general. We only covered how to do two analyses here, though five are possible under <em>Frequencies</em> in jamovi. Texas A&amp;M students can find these datalab.cc tutorials in the <em>LinkedIn Learning</em> series, available through the <em>Howdy!</em> portal.</p>
<p>Your textbook <span class="citation">(<a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft, 2019</a>)</span> obviously has a chapter on chi-square. But it also has a short tutorial on how to create contingency tables in Section 6.1.<a href="#fn58" class="footnote-ref" id="fnref58"><sup>58</sup></a></p>
<p><br/></p>
<div id="OutsideHelpOnGoodnessOfFit" class="section level3" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Goodness-of-fit test</h3>
<p>datalab.cc also provides a review of how to do chi-square goodness-of-fit tests. You can find it as video #47.</p>
<p>This is also in your main textbook <span class="citation">(<a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft, 2019, sec. 10.1</a>)</span>.</p>
<p><br/></p>
</div>
<div id="OutsideHelpOnChisquareTestOfIndependence" class="section level3" number="5.3.2">
<h3><span class="header-section-number">5.3.2</span> Chi-square test of independence</h3>
<p>The datalab.cc video for the chi-square test of independence (“Association”) is video #48.</p>
<p>This is also in your main textbook <span class="citation">(<a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft, 2019, sec. 10.2</a>)</span>.</p>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" line-spacing="2">
<div id="ref-BickelHammelOconnell1975" class="csl-entry">
Bickel, P. J., Hammel, E. A., &amp; O’Connell, J. W. (1975). Sex bias in graduate admissions: Data from berkeley. <em>Science</em>, <em>187</em>(4175), 398–404. Retrieved from <a href="http://www.jstor.org/stable/1739581">http://www.jstor.org/stable/1739581</a>
</div>
<div id="ref-Cohen1988" class="csl-entry">
Cohen, J. (1988). <em>Statistical power analysis for the behavioral sciences</em> (2nd ed.). New York, NY: Routlege.
</div>
<div id="ref-lsj" class="csl-entry">
Navarro, D. J., &amp; Foxcroft, D. R. (2019). Learning statistics with jamovi: A tutorial for psychology students and other beginners (Version 0.70). <a href="https://doi.org/10.24384/hgc3-7p15">https://doi.org/10.24384/hgc3-7p15</a>
</div>
<div id="ref-datalab.cc" class="csl-entry">
Poulson, B. (2019). <em>Datalab.cc</em>. Retrieved from <a href="https://datalab.cc/">https://datalab.cc/</a>
</div>
<div id="ref-R-base" class="csl-entry">
R Core Team. (2021). <em>R: A language and environment for statistical computing</em>. Retrieved from <a href="https://www.R-project.org/">https://www.R-project.org/</a>
</div>
<div id="ref-RaskinTerry1988" class="csl-entry">
Raskin, R., &amp; Terry, H. (1988). A principal-components analysis of the narcissistic personality inventory and further evidence of its construct validity. <em>Journal of Personality and Social Psychology</em>, <em>54</em>(5), 890–902. Retrieved from <a href="http://proxy.library.tamu.edu.srv-proxy1.library.tamu.edu/login?url=http://search.ebscohost.com/login.aspx?direct=true&amp;db=pdh&amp;AN=1988-25254-001&amp;site=ehost-live">http://proxy.library.tamu.edu.srv-proxy1.library.tamu.edu/login?url=http://search.ebscohost.com/login.aspx?direct=true&amp;db=pdh&amp;AN=1988-25254-001&amp;site=ehost-live</a>
</div>
<div id="ref-Turing1950" class="csl-entry">
Turing, A. M. (1950). <span class="nocase">I.—Computing Machinery and Intelligence</span>. <em>Mind</em>, <em>LIX</em>(236), 433–460. <a href="https://doi.org/10.1093/mind/LIX.236.433">https://doi.org/10.1093/mind/LIX.236.433</a>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="54">
<li id="fn54"><p>This isn’t even likely for any data you ever collect, unless you are analyzing coin flips, or dice throws (which you are unlikely to be doing).<a href="CategoricalDataAnalysis.html#fnref54" class="footnote-back">↩︎</a></p></li>
<li id="fn55"><p>The reason that <em>Counts</em> is optional is that it is summarized data. Thus, it is not “tidy,” <em>per se</em>. One could also do this chi-square if each row corresponded to one person, without the <em>Count</em> variable. This would have been a data set with 4,526 rows. In fact, this is normally the way data is collected. In this case, jamovi would have just counted the relevant numbers of rows instead of having them provided in an extra variable.<a href="CategoricalDataAnalysis.html#fnref55" class="footnote-back">↩︎</a></p></li>
<li id="fn56"><p>This is clearly a spin on Alan Turing’s <span class="citation">(<a href="#ref-Turing1950" role="doc-biblioref">1950</a>)</span> <a href="https://en.wikipedia.org/wiki/Turing_test">Turing Test</a><a href="CategoricalDataAnalysis.html#fnref56" class="footnote-back">↩︎</a></p></li>
<li id="fn57"><p>You could do this the other way around; it’s the same. But this is the way it was done in <span class="citation"><a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft</a> (<a href="#ref-lsj" role="doc-biblioref">2019</a>)</span>. We do the same here so as to reduce confusion.<a href="CategoricalDataAnalysis.html#fnref57" class="footnote-back">↩︎</a></p></li>
<li id="fn58"><p>The data for this little tutorial in <span class="citation"><a href="#ref-lsj" role="doc-biblioref">Navarro &amp; Foxcroft</a> (<a href="#ref-lsj" role="doc-biblioref">2019</a>)</span> are from <em>In the Night Garden</em>, a television show for really young children that isn’t shown in the US, but the main author (Bolger) got to see extensively while living in Canada when his son was very young. It has achieved some sort of cult status even among adults, who often find it so remarkably bizarre as to be entertaining even for them (at least for short stretches). The website for it is <a href="https://www.inthenightgarden.co.uk/">here</a> in case you are interested in a truly strange children’s show.<a href="CategoricalDataAnalysis.html#fnref58" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="DataVisualization.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ComparingTwoMeans.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "none",
"sharing": {
"github": true,
"facebook": false
}
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
