<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 8 Comparing several means | A Lab Manual for PSYC 301: Elementary Statistics for Psychology</title>
  <meta name="description" content="This is a lab manual for PSYC 301: Elementary Statistics for Psychology. It is an open educational resource (OER), so there is no charge to students." />
  <meta name="generator" content="bookdown 0.20.3 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 8 Comparing several means | A Lab Manual for PSYC 301: Elementary Statistics for Psychology" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://patrickabolger.github.io/ElemStatsLabManual/" />
  
  <meta property="og:description" content="This is a lab manual for PSYC 301: Elementary Statistics for Psychology. It is an open educational resource (OER), so there is no charge to students." />
  <meta name="github-repo" content="patrickabolger/ElemStatsLabManual" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 8 Comparing several means | A Lab Manual for PSYC 301: Elementary Statistics for Psychology" />
  
  <meta name="twitter:description" content="This is a lab manual for PSYC 301: Elementary Statistics for Psychology. It is an open educational resource (OER), so there is no charge to students." />
  



<meta name="date" content="2020-09-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="CorrAndLinearReg.html"/>
<link rel="next" href="FactorialAnova.html"/>
<script src="libs/header-attrs-2.3/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />



<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Lab Manual for PSYC 301: Elementary Statistics for Psychology</a></li>
<li><a href="./">Patrick Bolger, PhD.</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#goals"><i class="fa fa-check"></i><b>0.1</b> Goals</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#Resources"><i class="fa fa-check"></i><b>0.2</b> Resources</a>
<ul>
<li class="chapter" data-level="0.2.1" data-path="index.html"><a href="index.html#FixedResources"><i class="fa fa-check"></i><b>0.2.1</b> Fixed resources</a></li>
<li class="chapter" data-level="0.2.2" data-path="index.html"><a href="index.html#Software"><i class="fa fa-check"></i><b>0.2.2</b> Software</a></li>
</ul></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#RationaleForJamovi"><i class="fa fa-check"></i><b>0.3</b> Rationale for jamovi</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#OrganizationOfThisManual"><i class="fa fa-check"></i><b>0.4</b> Organization of this manual</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#MainOutcomeOfClass"><i class="fa fa-check"></i><b>0.5</b> Main outcome of class</a></li>
</ul></li>
<li class="part"><span><b>I Basics</b></span></li>
<li class="chapter" data-level="1" data-path="GettingUsedtoJamovi.html"><a href="GettingUsedtoJamovi.html"><i class="fa fa-check"></i><b>1</b> Getting used to jamovi</a>
<ul>
<li class="chapter" data-level="1.1" data-path="GettingUsedtoJamovi.html"><a href="GettingUsedtoJamovi.html#DownloadingAndInstallingJamovi"><i class="fa fa-check"></i><b>1.1</b> Downloading and installing</a></li>
<li class="chapter" data-level="1.2" data-path="GettingUsedtoJamovi.html"><a href="GettingUsedtoJamovi.html#NavigatingJamovi"><i class="fa fa-check"></i><b>1.2</b> Navigation</a></li>
<li class="chapter" data-level="1.3" data-path="GettingUsedtoJamovi.html"><a href="GettingUsedtoJamovi.html#OutsideHelpOnBasics"><i class="fa fa-check"></i><b>1.3</b> Outside help on basics</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="GettingUsedtoJamovi.html"><a href="GettingUsedtoJamovi.html#OutsideHelpOnOveralIntroduction"><i class="fa fa-check"></i><b>1.3.1</b> Overall introduction</a></li>
<li class="chapter" data-level="1.3.2" data-path="GettingUsedtoJamovi.html"><a href="GettingUsedtoJamovi.html#OutsideHelpOnDownloadingAndInstalling"><i class="fa fa-check"></i><b>1.3.2</b> Downloading and installing</a></li>
<li class="chapter" data-level="1.3.3" data-path="GettingUsedtoJamovi.html"><a href="GettingUsedtoJamovi.html#OutsideHelpOnNavigating"><i class="fa fa-check"></i><b>1.3.3</b> Navigating</a></li>
<li class="chapter" data-level="1.3.4" data-path="GettingUsedtoJamovi.html"><a href="GettingUsedtoJamovi.html#OutsideHelpOnModules"><i class="fa fa-check"></i><b>1.3.4</b> Modules</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="GettingUsedtoJamovi.html"><a href="GettingUsedtoJamovi.html#ConclusionOfBasics"><i class="fa fa-check"></i><b>1.4</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html"><i class="fa fa-check"></i><b>2</b> Basic data operations</a>
<ul>
<li class="chapter" data-level="2.1" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#Manualling"><i class="fa fa-check"></i><b>2.1</b> Entering data manually</a></li>
<li class="chapter" data-level="2.2" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#Opening"><i class="fa fa-check"></i><b>2.2</b> Opening data files</a></li>
<li class="chapter" data-level="2.3" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#Importing"><i class="fa fa-check"></i><b>2.3</b> Importing data</a></li>
<li class="chapter" data-level="2.4" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#Exporting"><i class="fa fa-check"></i><b>2.4</b> Exporting data</a></li>
<li class="chapter" data-level="2.5" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#ManipulatingData"><i class="fa fa-check"></i><b>2.5</b> Manipulating data</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#ComputingNewVariables"><i class="fa fa-check"></i><b>2.5.1</b> Computing new variables</a></li>
<li class="chapter" data-level="2.5.2" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#FilteringData"><i class="fa fa-check"></i><b>2.5.2</b> Filtering data</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#GeneralNoteUnderstandingTidyness"><i class="fa fa-check"></i><b>2.6</b> General note: Understanding <em>tidy</em>-ness</a></li>
<li class="chapter" data-level="2.7" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#OutsideHelpOnBasicDataOperations"><i class="fa fa-check"></i><b>2.7</b> Outside help on basic data preparation</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#OutsideHelpOnEnteringData"><i class="fa fa-check"></i><b>2.7.1</b> Entering and adjusting data</a></li>
<li class="chapter" data-level="2.7.2" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#OutsideHelpOnOpeningData"><i class="fa fa-check"></i><b>2.7.2</b> Opening data</a></li>
<li class="chapter" data-level="2.7.3" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#OutsideHelpOnImportingData"><i class="fa fa-check"></i><b>2.7.3</b> Importing data</a></li>
<li class="chapter" data-level="2.7.4" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#OutsideHelpOnRecodingVariables"><i class="fa fa-check"></i><b>2.7.4</b> Recoding variables</a></li>
<li class="chapter" data-level="2.7.5" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#OutsideHelpOnGeneratingRandomData"><i class="fa fa-check"></i><b>2.7.5</b> Generating random data</a></li>
<li class="chapter" data-level="2.7.6" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#OutsideHelpOnTransormingVariables"><i class="fa fa-check"></i><b>2.7.6</b> Transforming variables</a></li>
<li class="chapter" data-level="2.7.7" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#OutsideHelpOnFilteringData"><i class="fa fa-check"></i><b>2.7.7</b> Filtering data</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#BasicDataPreprationPracticeExercises"><i class="fa fa-check"></i><b>2.8</b> Practice Exercises</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#PracManualing"><i class="fa fa-check"></i><b>2.8.1</b> Practice entering data</a></li>
<li class="chapter" data-level="2.8.2" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#PracticeExporting"><i class="fa fa-check"></i><b>2.8.2</b> Practice exporting</a></li>
<li class="chapter" data-level="2.8.3" data-path="BasicDataOperations.html"><a href="BasicDataOperations.html#PracticeImporting"><i class="fa fa-check"></i><b>2.8.3</b> Practice importing</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html"><i class="fa fa-check"></i><b>3</b> Descriptive statistics</a>
<ul>
<li class="chapter" data-level="3.1" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#OverviewOfDescriptiveStats"><i class="fa fa-check"></i><b>3.1</b> Overview</a></li>
<li class="chapter" data-level="3.2" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#DescriptivesInJamovi"><i class="fa fa-check"></i><b>3.2</b> Descriptives in jamovi</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#SummarizingContinuousVariables"><i class="fa fa-check"></i><b>3.2.1</b> Summarizing continuous variables</a></li>
<li class="chapter" data-level="3.2.2" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#GroupedSummaries"><i class="fa fa-check"></i><b>3.2.2</b> Grouped summaries</a></li>
<li class="chapter" data-level="3.2.3" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#Frequencies"><i class="fa fa-check"></i><b>3.2.3</b> Frequencies</a></li>
<li class="chapter" data-level="3.2.4" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#reporting-data-summaries"><i class="fa fa-check"></i><b>3.2.4</b> Reporting data summaries</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#OutsideHelpOnDescriptives"><i class="fa fa-check"></i><b>3.3</b> Outside help on descriptives</a></li>
<li class="chapter" data-level="3.4" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#PracticeSummarizingAndReporting"><i class="fa fa-check"></i><b>3.4</b> Practice summarizing and reporting</a></li>
<li class="chapter" data-level="3.5" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#GlossaryOfDescriptives"><i class="fa fa-check"></i><b>3.5</b> Glossary of descriptives</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#CentralTendency"><i class="fa fa-check"></i><b>3.5.1</b> Central tendency</a></li>
<li class="chapter" data-level="3.5.2" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#Dispersion"><i class="fa fa-check"></i><b>3.5.2</b> Dispersion</a></li>
<li class="chapter" data-level="3.5.3" data-path="DescriptiveStats.html"><a href="DescriptiveStats.html#diagnostics"><i class="fa fa-check"></i><b>3.5.3</b> Diagnostics</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="DataVisualization.html"><a href="DataVisualization.html"><i class="fa fa-check"></i><b>4</b> Data visualizations</a>
<ul>
<li class="chapter" data-level="4.1" data-path="DataVisualization.html"><a href="DataVisualization.html#Histograms"><i class="fa fa-check"></i><b>4.1</b> Histograms</a></li>
<li class="chapter" data-level="4.2" data-path="DataVisualization.html"><a href="DataVisualization.html#Boxplots"><i class="fa fa-check"></i><b>4.2</b> Boxplots</a></li>
<li class="chapter" data-level="4.3" data-path="DataVisualization.html"><a href="DataVisualization.html#ViolinPlots"><i class="fa fa-check"></i><b>4.3</b> Violin plots</a></li>
<li class="chapter" data-level="4.4" data-path="DataVisualization.html"><a href="DataVisualization.html#DotPlots"><i class="fa fa-check"></i><b>4.4</b> Dot plots</a></li>
<li class="chapter" data-level="4.5" data-path="DataVisualization.html"><a href="DataVisualization.html#Barplots"><i class="fa fa-check"></i><b>4.5</b> Bar plots</a></li>
<li class="chapter" data-level="4.6" data-path="DataVisualization.html"><a href="DataVisualization.html#QQPlots"><i class="fa fa-check"></i><b>4.6</b> Q-Q plots</a></li>
<li class="chapter" data-level="4.7" data-path="DataVisualization.html"><a href="DataVisualization.html#outside-help-on-visualization"><i class="fa fa-check"></i><b>4.7</b> Outside help on visualization</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="DataVisualization.html"><a href="DataVisualization.html#OutsideHelpOnHistograms"><i class="fa fa-check"></i><b>4.7.1</b> Histograms</a></li>
<li class="chapter" data-level="4.7.2" data-path="DataVisualization.html"><a href="DataVisualization.html#OutsideHelpOnBoxPlots"><i class="fa fa-check"></i><b>4.7.2</b> Boxplots</a></li>
<li class="chapter" data-level="4.7.3" data-path="DataVisualization.html"><a href="DataVisualization.html#OutsideHelpOnViolinPlots"><i class="fa fa-check"></i><b>4.7.3</b> Violin plots</a></li>
<li class="chapter" data-level="4.7.4" data-path="DataVisualization.html"><a href="DataVisualization.html#OutsideHelpOnDotPlots"><i class="fa fa-check"></i><b>4.7.4</b> Dot plots</a></li>
<li class="chapter" data-level="4.7.5" data-path="DataVisualization.html"><a href="DataVisualization.html#bar-plots-outsidehelponbarplots"><i class="fa fa-check"></i><b>4.7.5</b> Bar plots (#OutsideHelpOnBarPlots)</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Inferential statistics</b></span></li>
<li class="chapter" data-level="5" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html"><i class="fa fa-check"></i><b>5</b> Categorical data analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html#ChiSquareGoodnessOfFit"><i class="fa fa-check"></i><b>5.1</b> Chi-square goodness-of-fit test</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html#ChiSquareGoodnessOfFitBasicCards"><i class="fa fa-check"></i><b>5.1.1</b> Basic: The Cards data</a></li>
<li class="chapter" data-level="5.1.2" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html#ChiSquareGoodnessOfFitAdvancedUCBAdmit"><i class="fa fa-check"></i><b>5.1.2</b> Advanced: Student admissions at UC Berkeley</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html#ChiSquareTestOfIndependence"><i class="fa fa-check"></i><b>5.2</b> Chi-square test of independence</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html#ChiSquareTestOfIndependenceChapek9"><i class="fa fa-check"></i><b>5.2.1</b> Basic: The <em>Chapek 9</em> data</a></li>
<li class="chapter" data-level="5.2.2" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html#NarcissisticPersonalityInventory"><i class="fa fa-check"></i><b>5.2.2</b> Advanced: The Narcissistic Personality Inventory</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html#OutsideHelpOnChisquare"><i class="fa fa-check"></i><b>5.3</b> Outside help on chi-square</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html#OutsideHelpOnGoodnessOfFit"><i class="fa fa-check"></i><b>5.3.1</b> Goodness-of-fit test</a></li>
<li class="chapter" data-level="5.3.2" data-path="CategoricalDataAnalysis.html"><a href="CategoricalDataAnalysis.html#OutsideHelpOnChisquareTestOfIndependence"><i class="fa fa-check"></i><b>5.3.2</b> Chi-square test of independence</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html"><i class="fa fa-check"></i><b>6</b> Comparing two means</a>
<ul>
<li class="chapter" data-level="6.1" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#DoingIndSamplesTTest"><i class="fa fa-check"></i><b>6.1</b> The independent-samples <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#IndSamplesDrHarpo"><i class="fa fa-check"></i><b>6.1.1</b> Basic: Dr. Harpo’s statistics class</a></li>
<li class="chapter" data-level="6.1.2" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#IndSamplesConspiracyData"><i class="fa fa-check"></i><b>6.1.2</b> Advanced 1: The conspiracy data</a></li>
<li class="chapter" data-level="6.1.3" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#IndSamplesSpokeWrit"><i class="fa fa-check"></i><b>6.1.3</b> Advanced 2: Spoken vs. written pitches</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#DoingPairedSamplesTTest"><i class="fa fa-check"></i><b>6.2</b> The paired-samples <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#PairedSamplesChicoBasicData"><i class="fa fa-check"></i><b>6.2.1</b> Basic: The <em>Chico</em> data</a></li>
<li class="chapter" data-level="6.2.2" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#PairedSamplesChicoAdvancedData"><i class="fa fa-check"></i><b>6.2.2</b> Advanced 1: Randomly generated <em>Chico</em> data</a></li>
<li class="chapter" data-level="6.2.3" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#PairedSamplesSingingParents"><i class="fa fa-check"></i><b>6.2.3</b> Advanced 2: Singing parents</a></li>
<li class="chapter" data-level="6.2.4" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#PairedSamplesSingingParentsStudentTask"><i class="fa fa-check"></i><b>6.2.4</b> Your tasks</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#OutsideHelpOnComparingTwoMeans"><i class="fa fa-check"></i><b>6.3</b> Outside help on <em>t</em>-tests</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#OutsideHelpOnIndependentSamplesT"><i class="fa fa-check"></i><b>6.3.1</b> Independent samples <em>t</em>-test</a></li>
<li class="chapter" data-level="6.3.2" data-path="ComparingTwoMeans.html"><a href="ComparingTwoMeans.html#OutsideHelpOnPairedSamplesT"><i class="fa fa-check"></i><b>6.3.2</b> Paired samples <em>t</em>-test</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="CorrAndLinearReg.html"><a href="CorrAndLinearReg.html"><i class="fa fa-check"></i><b>7</b> Correlation and linear regression</a>
<ul>
<li class="chapter" data-level="7.1" data-path="CorrAndLinearReg.html"><a href="CorrAndLinearReg.html#Correlations"><i class="fa fa-check"></i><b>7.1</b> Correlations</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="CorrAndLinearReg.html"><a href="CorrAndLinearReg.html#BasicCorrelationParenthood"><i class="fa fa-check"></i><b>7.1.1</b> Basic: Parenthood data</a></li>
<li class="chapter" data-level="7.1.2" data-path="CorrAndLinearReg.html"><a href="CorrAndLinearReg.html#AdvancedCorrelationSPRING2020"><i class="fa fa-check"></i><b>7.1.2</b> Advanced</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="CorrAndLinearReg.html"><a href="CorrAndLinearReg.html#LinearRegression"><i class="fa fa-check"></i><b>7.2</b> Linear regression</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="CorrAndLinearReg.html"><a href="CorrAndLinearReg.html#BasicRegressionParenthood"><i class="fa fa-check"></i><b>7.2.1</b> Basic: Parenthood data (again)</a></li>
<li class="chapter" data-level="7.2.2" data-path="CorrAndLinearReg.html"><a href="CorrAndLinearReg.html#AdvancedRegressionSPRING2020"><i class="fa fa-check"></i><b>7.2.2</b> Advanced:</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="CorrAndLinearReg.html"><a href="CorrAndLinearReg.html#MultipleLinearRegression"><i class="fa fa-check"></i><b>7.3</b> Multiple linear regression</a></li>
<li class="chapter" data-level="7.4" data-path="CorrAndLinearReg.html"><a href="CorrAndLinearReg.html#OutsideHelpOnCorrelation"><i class="fa fa-check"></i><b>7.4</b> Outside help on correlation</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ComparingSeveralMeans.html"><a href="ComparingSeveralMeans.html"><i class="fa fa-check"></i><b>8</b> Comparing several means</a>
<ul>
<li class="chapter" data-level="8.1" data-path="ComparingSeveralMeans.html"><a href="ComparingSeveralMeans.html#OnewayAnova"><i class="fa fa-check"></i><b>8.1</b> The One-Way ANOVA</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="ComparingSeveralMeans.html"><a href="ComparingSeveralMeans.html#OnewayAnovaClinicalTrialData"><i class="fa fa-check"></i><b>8.1.1</b> Basic: Clinical Trial data</a></li>
<li class="chapter" data-level="8.1.2" data-path="ComparingSeveralMeans.html"><a href="ComparingSeveralMeans.html#advanced"><i class="fa fa-check"></i><b>8.1.2</b> Advanced</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="ComparingSeveralMeans.html"><a href="ComparingSeveralMeans.html#repeated-measures-one-way-anova"><i class="fa fa-check"></i><b>8.2</b> Repeated-measures One-Way ANOVA</a></li>
<li class="chapter" data-level="8.3" data-path="ComparingSeveralMeans.html"><a href="ComparingSeveralMeans.html#outside-help-on-one-way-anova"><i class="fa fa-check"></i><b>8.3</b> Outside help on One-Way ANOVA</a></li>
<li class="chapter" data-level="8.4" data-path="ComparingSeveralMeans.html"><a href="ComparingSeveralMeans.html#PracticingOnewayAnova"><i class="fa fa-check"></i><b>8.4</b> Extra practice One-Way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="FactorialAnova.html"><a href="FactorialAnova.html"><i class="fa fa-check"></i><b>9</b> Factorial ANOVA</a>
<ul>
<li class="chapter" data-level="9.1" data-path="FactorialAnova.html"><a href="FactorialAnova.html#BasicFactorialAnovaJoyzepam"><i class="fa fa-check"></i><b>9.1</b> Basic: joyzepam data</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="FactorialAnova.html"><a href="FactorialAnova.html#BasicFactorialAnovaJoyzepamObtainingTheData"><i class="fa fa-check"></i><b>9.1.1</b> Obtaining the data</a></li>
<li class="chapter" data-level="9.1.2" data-path="FactorialAnova.html"><a href="FactorialAnova.html#BasicFactorialAnovaJoyzepamImplementing"><i class="fa fa-check"></i><b>9.1.2</b> Implementing the procedure</a></li>
<li class="chapter" data-level="9.1.3" data-path="FactorialAnova.html"><a href="FactorialAnova.html#BasicFactorialAnovaJoyzepamInterpreting"><i class="fa fa-check"></i><b>9.1.3</b> Interpreting the output</a></li>
<li class="chapter" data-level="9.1.4" data-path="FactorialAnova.html"><a href="FactorialAnova.html#BasicFactorialAnovaJoyzepamReporting"><i class="fa fa-check"></i><b>9.1.4</b> Reporting the output</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="FactorialAnova.html"><a href="FactorialAnova.html#AdvancedFactorialAnova_NAME"><i class="fa fa-check"></i><b>9.2</b> Advanced: advanced data NAME</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="FactorialAnova.html"><a href="FactorialAnova.html#AdvancedFactorialAnova_NAMEObtainingTheData"><i class="fa fa-check"></i><b>9.2.1</b> Obtaining the data</a></li>
<li class="chapter" data-level="9.2.2" data-path="FactorialAnova.html"><a href="FactorialAnova.html#AdvancedFactorialAnova_NAMEImplementing"><i class="fa fa-check"></i><b>9.2.2</b> Implementing the procedure</a></li>
<li class="chapter" data-level="9.2.3" data-path="FactorialAnova.html"><a href="FactorialAnova.html#AdvancedFactorialAnova_NAMEInterpreting"><i class="fa fa-check"></i><b>9.2.3</b> Interpreting the output</a></li>
<li class="chapter" data-level="9.2.4" data-path="FactorialAnova.html"><a href="FactorialAnova.html#AdvancedFactorialAnova_NAMEReporting"><i class="fa fa-check"></i><b>9.2.4</b> Reporting the output</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="FactorialAnova.html"><a href="FactorialAnova.html#ConclusionOfFactorialAnova"><i class="fa fa-check"></i><b>9.3</b> Conclusion</a></li>
<li class="chapter" data-level="9.4" data-path="FactorialAnova.html"><a href="FactorialAnova.html#outside-help-on-factorial-anova"><i class="fa fa-check"></i><b>9.4</b> Outside help on factorial ANOVA</a></li>
<li class="chapter" data-level="9.5" data-path="FactorialAnova.html"><a href="FactorialAnova.html#PracticingFactorialAnova"><i class="fa fa-check"></i><b>9.5</b> Extra practice on factorial ANOVA</a></li>
</ul></li>
<li class="part"><span><b>III Research projects</b></span></li>
<li class="chapter" data-level="10" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html"><i class="fa fa-check"></i><b>10</b> Survey Design and Data Collection</a>
<ul>
<li class="chapter" data-level="10.1" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#ResearchProjectsOverview"><i class="fa fa-check"></i><b>10.1</b> Unit Overview</a></li>
<li class="chapter" data-level="10.2" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#SurveyDesignAndDataCollectionChapterOverview"><i class="fa fa-check"></i><b>10.2</b> Chapter Overview</a></li>
<li class="chapter" data-level="10.3" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#WhatIsScience"><i class="fa fa-check"></i><b>10.3</b> What is <em>Science</em>?</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#WhatIsMeasurement"><i class="fa fa-check"></i><b>10.3.1</b> What is <em>measurement</em>?</a></li>
<li class="chapter" data-level="10.3.2" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#WhatAreConstructs"><i class="fa fa-check"></i><b>10.3.2</b> What are <em>constructs</em>?</a></li>
<li class="chapter" data-level="10.3.3" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#WhatIsOperationalization"><i class="fa fa-check"></i><b>10.3.3</b> What is <em>operationalization</em>?</a></li>
<li class="chapter" data-level="10.3.4" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#WhatAreVariables"><i class="fa fa-check"></i><b>10.3.4</b> What are <em>variables</em>?</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#DesigningTheSurvey"><i class="fa fa-check"></i><b>10.4</b> Designing the survey</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#VariablesInYourStudy"><i class="fa fa-check"></i><b>10.4.1</b> Variables in your study</a></li>
<li class="chapter" data-level="10.4.2" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#MoreInformationOnSurveyQuestions"><i class="fa fa-check"></i><b>10.4.2</b> More information on survey questions</a></li>
<li class="chapter" data-level="10.4.3" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#SummaryOfSurveyDesignAssignment"><i class="fa fa-check"></i><b>10.4.3</b> Summary of <em>Survey Design</em> assignment</a></li>
<li class="chapter" data-level="10.4.4" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#OutsideHelpOnSurveys"><i class="fa fa-check"></i><b>10.4.4</b> Outside help on surveys</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="SurveyDesignAndDataCollection.html"><a href="SurveyDesignAndDataCollection.html#CollectingTheData"><i class="fa fa-check"></i><b>10.5</b> Collecting the Data</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html"><i class="fa fa-check"></i><b>11</b> Data Preparation and Analyses</a>
<ul>
<li class="chapter" data-level="11.1" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#DataPreparationAndAnalysesChapterOverview"><i class="fa fa-check"></i><b>11.1</b> Chapter overview</a></li>
<li class="chapter" data-level="11.2" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataExportingDataFromGoogleForms"><i class="fa fa-check"></i><b>11.2</b> Exporting data from Google Forms</a></li>
<li class="chapter" data-level="11.3" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataImportingTheData"><i class="fa fa-check"></i><b>11.3</b> Importing the data into jamovi</a></li>
<li class="chapter" data-level="11.4" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataCleaningUpTheData"><i class="fa fa-check"></i><b>11.4</b> Cleaning up the data</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataRenamingVariables"><i class="fa fa-check"></i><b>11.4.1</b> Renaming variables</a></li>
<li class="chapter" data-level="11.4.2" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataRemovingVariables"><i class="fa fa-check"></i><b>11.4.2</b> Removing variables</a></li>
<li class="chapter" data-level="11.4.3" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataAdjustingVariables"><i class="fa fa-check"></i><b>11.4.3</b> Adjusting variables</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataFinalStepsBeforeAnalysis"><i class="fa fa-check"></i><b>11.5</b> Final steps before analysis</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataFilteringData"><i class="fa fa-check"></i><b>11.5.1</b> Filtering data</a></li>
<li class="chapter" data-level="11.5.2" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataReverseScoring"><i class="fa fa-check"></i><b>11.5.2</b> Reverse-scoring</a></li>
<li class="chapter" data-level="11.5.3" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataCalculatingZScores"><i class="fa fa-check"></i><b>11.5.3</b> Calculating <em>z</em>-scores</a></li>
<li class="chapter" data-level="11.5.4" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataCalculatingCronbachsAlpha"><i class="fa fa-check"></i><b>11.5.4</b> Calculating Cronbach’s alpha</a></li>
<li class="chapter" data-level="11.5.5" data-path="DataPreparationAndAnalyses.html"><a href="DataPreparationAndAnalyses.html#PreparingDataCreatingACompositeVariable"><i class="fa fa-check"></i><b>11.5.5</b> Creating a composite variable</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Writing</b></span></li>
<li class="chapter" data-level="12" data-path="ReportingResearch.html"><a href="ReportingResearch.html"><i class="fa fa-check"></i><b>12</b> Reporting research</a>
<ul>
<li class="chapter" data-level="12.1" data-path="ReportingResearch.html"><a href="ReportingResearch.html#TheBroaderContext"><i class="fa fa-check"></i><b>12.1</b> The broader context</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="ReportingResearch.html"><a href="ReportingResearch.html#EducationCircles"><i class="fa fa-check"></i><b>12.1.1</b> The education circle</a></li>
<li class="chapter" data-level="12.1.2" data-path="ReportingResearch.html"><a href="ReportingResearch.html#ResearchCircle"><i class="fa fa-check"></i><b>12.1.2</b> The research circle</a></li>
<li class="chapter" data-level="12.1.3" data-path="ReportingResearch.html"><a href="ReportingResearch.html#ResearchGenre"><i class="fa fa-check"></i><b>12.1.3</b> The research genre</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="ReportingResearch.html"><a href="ReportingResearch.html#PurposeOfThisClass"><i class="fa fa-check"></i><b>12.2</b> Purpose of writing in this class</a></li>
<li class="chapter" data-level="12.3" data-path="ReportingResearch.html"><a href="ReportingResearch.html#TheGenreOfScience"><i class="fa fa-check"></i><b>12.3</b> The genre of science</a></li>
<li class="chapter" data-level="12.4" data-path="ReportingResearch.html"><a href="ReportingResearch.html#StyleGuides"><i class="fa fa-check"></i><b>12.4</b> Style guides</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="ReportingResearch.html"><a href="ReportingResearch.html#ApaStyle"><i class="fa fa-check"></i><b>12.4.1</b> APA style</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="ReportingResearch.html"><a href="ReportingResearch.html#IssuesNotExtensivelyCovered"><i class="fa fa-check"></i><b>12.5</b> Issues not extensively covered</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="ReportingResearch.html"><a href="ReportingResearch.html#CriticalThinking"><i class="fa fa-check"></i><b>12.5.1</b> Critical thinking</a></li>
<li class="chapter" data-level="12.5.2" data-path="ReportingResearch.html"><a href="ReportingResearch.html#MechanicsOfWriting"><i class="fa fa-check"></i><b>12.5.2</b> “Grammar”, clarity, and mechanics</a></li>
<li class="chapter" data-level="12.5.3" data-path="ReportingResearch.html"><a href="ReportingResearch.html#PacingTheWritingProcess"><i class="fa fa-check"></i><b>12.5.3</b> Pacing the writing process</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="ReportingResearch.html"><a href="ReportingResearch.html#OutsideHelpOnWritingUpResearch"><i class="fa fa-check"></i><b>12.6</b> Outside help on writing up research</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="ReportingResearch.html"><a href="ReportingResearch.html#research-papers-in-apa-format"><i class="fa fa-check"></i><b>12.6.1</b> Research papers in APA format</a></li>
<li class="chapter" data-level="12.6.2" data-path="ReportingResearch.html"><a href="ReportingResearch.html#WritingUpResearch"><i class="fa fa-check"></i><b>12.6.2</b> Writing up research</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html"><i class="fa fa-check"></i><b>13</b> Writing introductions</a>
<ul>
<li class="chapter" data-level="13.1" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#PurposeOfTheIntroduction"><i class="fa fa-check"></i><b>13.1</b> The purpose of the <em>Introduction</em></a></li>
<li class="chapter" data-level="13.2" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#StructureOfIntroductions"><i class="fa fa-check"></i><b>13.2</b> Structure of introductions</a></li>
<li class="chapter" data-level="13.3" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#ExamplesOfIntroductions"><i class="fa fa-check"></i><b>13.3</b> Examples of introductions</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#ExamplesOfOpeningSentencesOfIntroductions"><i class="fa fa-check"></i><b>13.3.1</b> Examples of opening sentences</a></li>
<li class="chapter" data-level="13.3.2" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#ExamplesOfTheLiteratureReview"><i class="fa fa-check"></i><b>13.3.2</b> Examples of the literature review</a></li>
<li class="chapter" data-level="13.3.3" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#ExamplesOfResearchQuestionsAndHypotheses"><i class="fa fa-check"></i><b>13.3.3</b> Examples of research questions and hypotheses</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#OutsideHelpOnIntroductions"><i class="fa fa-check"></i><b>13.4</b> Outside help on introductions</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#OutsideHelpOnIntroductionsOpeningSentences"><i class="fa fa-check"></i><b>13.4.1</b> Opening sentences</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#PWEFI1"><i class="fa fa-check"></i><b>13.5</b> Practice writing exercise 1</a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#PWEFI1SettingUpGroupsAndDocs"><i class="fa fa-check"></i><b>13.5.1</b> Setting up your groups and docs</a></li>
<li class="chapter" data-level="13.5.2" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#PWEFI1OpeningSentence"><i class="fa fa-check"></i><b>13.5.2</b> Opening sentence</a></li>
<li class="chapter" data-level="13.5.3" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#PWEFI1ResearchQuestion"><i class="fa fa-check"></i><b>13.5.3</b> Research question</a></li>
<li class="chapter" data-level="13.5.4" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#PWEFI1ResearchHypothesis"><i class="fa fa-check"></i><b>13.5.4</b> Research Hypothesis</a></li>
<li class="chapter" data-level="13.5.5" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#PWEFI1GeneralToSpecific"><i class="fa fa-check"></i><b>13.5.5</b> General-to-specific paragraphs</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#PWEFI2"><i class="fa fa-check"></i><b>13.6</b> Practice writing exercise 2</a></li>
<li class="chapter" data-level="13.7" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#WritingAssignment1"><i class="fa fa-check"></i><b>13.7</b> Writing Assignment #1</a>
<ul>
<li class="chapter" data-level="13.7.1" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#GeneralInstructionsOnWritingAssignment1"><i class="fa fa-check"></i><b>13.7.1</b> General Instructions</a></li>
<li class="chapter" data-level="13.7.2" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#SpecificInstructionsOnWritingAssignment1"><i class="fa fa-check"></i><b>13.7.2</b> Specific Instructions</a></li>
<li class="chapter" data-level="13.7.3" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#UploadingRoughDraftOfWritingAssignment1"><i class="fa fa-check"></i><b>13.7.3</b> Uploading the rough draft</a></li>
<li class="chapter" data-level="13.7.4" data-path="WritingIntroductions.html"><a href="WritingIntroductions.html#uploading-the-final-draft"><i class="fa fa-check"></i><b>13.7.4</b> Uploading the final draft</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html"><i class="fa fa-check"></i><b>14</b> Writing <em>Method</em> sections</a>
<ul>
<li class="chapter" data-level="14.1" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#PurposeOfTheMethodSection"><i class="fa fa-check"></i><b>14.1</b> Purpose of the Method section</a></li>
<li class="chapter" data-level="14.2" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#StructureOfMethodSections"><i class="fa fa-check"></i><b>14.2</b> Structure of Method sections</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#MethodSection1Participants"><i class="fa fa-check"></i><b>14.2.1</b> <em>Participants</em></a></li>
<li class="chapter" data-level="14.2.2" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#MethodSection2Materials"><i class="fa fa-check"></i><b>14.2.2</b> <em>Materials</em></a></li>
<li class="chapter" data-level="14.2.3" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#MethodSection3DesignAndAnalysis"><i class="fa fa-check"></i><b>14.2.3</b> <em>Design and Analysis</em></a></li>
<li class="chapter" data-level="14.2.4" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#MethodSection4Procedure"><i class="fa fa-check"></i><b>14.2.4</b> <em>Procedure</em></a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#OutsideHelpOnMethodsSections"><i class="fa fa-check"></i><b>14.3</b> Outside help on Method sections</a></li>
<li class="chapter" data-level="14.4" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#PWEFM1"><i class="fa fa-check"></i><b>14.4</b> Practice writing exercise 1</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#PWEFM1Participants"><i class="fa fa-check"></i><b>14.4.1</b> Participants</a></li>
<li class="chapter" data-level="14.4.2" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#PWEFM1MaterialsDesignProcedures"><i class="fa fa-check"></i><b>14.4.2</b> Materials, Design, and Procedures</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#WritingAssignment2"><i class="fa fa-check"></i><b>14.5</b> Writing Assignment #2</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#GeneralInstructionsOnWritingAssignment2"><i class="fa fa-check"></i><b>14.5.1</b> General Instructions</a></li>
<li class="chapter" data-level="14.5.2" data-path="WritingMethodSections.html"><a href="WritingMethodSections.html#SpecificInstructionsOnWritingAssignment2"><i class="fa fa-check"></i><b>14.5.2</b> Specific Instructions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html"><i class="fa fa-check"></i><b>15</b> Writing <em>Results</em> sections</a>
<ul>
<li class="chapter" data-level="15.1" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html#NoteOnWritingAssignments3And4"><i class="fa fa-check"></i><b>15.1</b> A note on Writing Assignments 3 and 4</a></li>
<li class="chapter" data-level="15.2" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html#StructureOfResultsSections"><i class="fa fa-check"></i><b>15.2</b> Structure of <em>Results</em> sections</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html#ExamplesOfResultsSections"><i class="fa fa-check"></i><b>15.2.1</b> Examples of <em>Results</em> sections</a></li>
<li class="chapter" data-level="15.2.2" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html#FormattingTablesInAPA"><i class="fa fa-check"></i><b>15.2.2</b> Formatting tables in APA</a></li>
<li class="chapter" data-level="15.2.3" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html#FormattingFiguresInAPA"><i class="fa fa-check"></i><b>15.2.3</b> Formatting figures in APA</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html#PWEFR"><i class="fa fa-check"></i><b>15.3</b> Practice writing exercise</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html#PWEFRFormingGroups"><i class="fa fa-check"></i><b>15.3.1</b> Forming groups</a></li>
<li class="chapter" data-level="15.3.2" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html#PWEFRGetStatisticalOutputReady"><i class="fa fa-check"></i><b>15.3.2</b> Get the statistical output ready</a></li>
<li class="chapter" data-level="15.3.3" data-path="WritingResultsSections.html"><a href="WritingResultsSections.html#PWEFRWriting"><i class="fa fa-check"></i><b>15.3.3</b> Writing</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html"><i class="fa fa-check"></i><b>16</b> Writing <em>Discussion</em> sections</a>
<ul>
<li class="chapter" data-level="16.1" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#StructureOfDiscussionSections"><i class="fa fa-check"></i><b>16.1</b> Purpose and structure of <em>Discussion</em> sections</a>
<ul>
<li class="chapter" data-level="16.1.1" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#StructureOfSingleStudyDiscussionSections"><i class="fa fa-check"></i><b>16.1.1</b> Single-study <em>Discussion</em> sections</a></li>
<li class="chapter" data-level="16.1.2" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#StructureOfMultipleStudyDiscussionSections"><i class="fa fa-check"></i><b>16.1.2</b> Multiple-study <em>Discussion</em> sections</a></li>
<li class="chapter" data-level="16.1.3" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#ExamplesOfDiscussionSections"><i class="fa fa-check"></i><b>16.1.3</b> Examples of <em>Discussion</em> sections</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#PWEFD"><i class="fa fa-check"></i><b>16.2</b> Practice writing exercise</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#PWEFDGettingReady"><i class="fa fa-check"></i><b>16.2.1</b> Getting ready</a></li>
<li class="chapter" data-level="16.2.2" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#PWEFDWriting"><i class="fa fa-check"></i><b>16.2.2</b> Writing</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#WritingAssignment3"><i class="fa fa-check"></i><b>16.3</b> Writing Assignment #3</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#GeneralInstructionsOnWritingAssignment3"><i class="fa fa-check"></i><b>16.3.1</b> General Instructions</a></li>
<li class="chapter" data-level="16.3.2" data-path="WritingDiscussionSections.html"><a href="WritingDiscussionSections.html#SpecificInstructionsOnWritingAssignment3"><i class="fa fa-check"></i><b>16.3.2</b> Specific Instructions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html"><i class="fa fa-check"></i><b>17</b> Writing <em>General Discussion</em> sections</a>
<ul>
<li class="chapter" data-level="17.1" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#NoteOnWritingAssignments4"><i class="fa fa-check"></i><b>17.1</b> A note on Writing Assignment 4</a></li>
<li class="chapter" data-level="17.2" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#StructureOfGeneralDiscussionSections"><i class="fa fa-check"></i><b>17.2</b> Structure of <em>General Discussion</em> sections</a></li>
<li class="chapter" data-level="17.3" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#ContentsOfGeneralDiscussionSections"><i class="fa fa-check"></i><b>17.3</b> Contents of <em>General Discussion</em> sections</a>
<ul>
<li class="chapter" data-level="17.3.1" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#ContentsOfGeneralDiscussionSectionsSynthesizing"><i class="fa fa-check"></i><b>17.3.1</b> Synthesizing</a></li>
<li class="chapter" data-level="17.3.2" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#ContentsOfGeneralDiscussionSectionsClarifying"><i class="fa fa-check"></i><b>17.3.2</b> Clarifying</a></li>
<li class="chapter" data-level="17.3.3" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#ContentsOfGeneralDiscussionSectionsConcluding"><i class="fa fa-check"></i><b>17.3.3</b> Concluding</a></li>
<li class="chapter" data-level="17.3.4" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#ExampleInAppendixI"><i class="fa fa-check"></i><b>17.3.4</b> Example in Appendix I</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#PWEFGD"><i class="fa fa-check"></i><b>17.4</b> Practice writing exercise</a>
<ul>
<li class="chapter" data-level="17.4.1" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#PWEFGDGettingReady"><i class="fa fa-check"></i><b>17.4.1</b> Getting ready</a></li>
<li class="chapter" data-level="17.4.2" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#PWEFGDWriting"><i class="fa fa-check"></i><b>17.4.2</b> Writing</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#WritingAssignment4"><i class="fa fa-check"></i><b>17.5</b> Writing Assignment #4</a>
<ul>
<li class="chapter" data-level="17.5.1" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#GeneralInstructionsOnWritingAssignment4"><i class="fa fa-check"></i><b>17.5.1</b> General Instructions</a></li>
<li class="chapter" data-level="17.5.2" data-path="WritingGeneralDiscussionSections.html"><a href="WritingGeneralDiscussionSections.html#SpecificInstructionsOnWritingAssignment4"><i class="fa fa-check"></i><b>17.5.2</b> Specific Instructions</a></li>
</ul></li>
</ul></li>
<li class="appendix"><span><b>Appendixes</b></span></li>
<li><a href="a-introduction-example.html#a-introduction-example">A: <em>Introduction</em> example</a></li>
<li><a href="b-introduction-rubric.html#b-introduction-rubric">B: <em>Introduction</em> rubric</a></li>
<li><a href="c-methods-example.html#c-methods-example">C: <em>Methods</em> example</a></li>
<li><a href="d-method-rubric.html#d-method-rubric">D: <em>Method</em> rubric</a></li>
<li><a href="e-results-example.html#e-results-example">E: <em>Results</em> example</a></li>
<li><a href="f-results-rubric.html#f-results-rubric">F: <em>Results</em> rubric</a></li>
<li><a href="g-discussion-example.html#g-discussion-example">G: <em>Discussion</em> example</a></li>
<li><a href="h-discussion-rubric.html#h-discussion-rubric">H: <em>Discussion</em> rubric</a></li>
<li><a href="i-general-discussion-example.html#i-general-discussion-example">I: <em>General Discussion</em> example</a></li>
<li><a href="j-general-discussion-rubric.html#j-general-discussion-rubric">J: <em>General Discussion</em> rubric</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
    sharing:

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Lab Manual for PSYC 301: Elementary Statistics for Psychology</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ComparingSeveralMeans" class="section level1" number="8">
<h1><span class="header-section-number">Chapter 8</span> Comparing several means</h1>
<p>This chapter explains how to use jamovi to analyze a continuous outcome variable when it is split into three or more levels of a categorical predictor variable. It follows the main textbook <span class="citation">(Navarro &amp; Foxcroft, <a href="#ref-lsj" role="doc-biblioref">2019</a>, Chapter 13)</span></p>
<p>For example, you might analyze something like attitude towards increasing taxes to fund public education. And your participants might have been, say, Democrats, Republicans, and “Others.” In this case, you could look at their mean responses by group, and figure out if any of these means were significantly different from any of the others.</p>
<p><br/></p>
<div id="OnewayAnova" class="section level2" number="8.1">
<h2><span class="header-section-number">8.1</span> The One-Way ANOVA</h2>
<p>Carrying out One-Way ANOVA is covered in your main textbook <span class="citation">(Navarro &amp; Foxcroft, <a href="#ref-lsj" role="doc-biblioref">2019</a>, Sections 13.1 to 13.7)</span>.</p>
<p>In this test, we are interested in whether three or more groups comprising independent observations differ with each on a single, continuous outcome variable.<a href="#fn73" class="footnote-ref" id="fnref73"><sup>73</sup></a></p>
<p>The <em>F</em>-test is the calculation of a particular kind of ratio, the <em>F</em>-ratio (unsurprisingly!). It is the ratio of between-subjects variance (<em>Mean Squares Between</em>) divided by the within-subjects variance (<em>Mean Squares Within</em>). Each of these, respectively, is the ratio of the <em>Sum of Squares</em> (between or within) divided by the <em>degrees of freedom</em> (between or within). Thus:</p>
<p><span class="math display">\[F= \frac{MeanSquares_{between}}{MeanSquares_{within}} = \frac{\frac{SumOfSquares_{betweeen}}{DegreesOfFreedom_{between}}}{\frac{SumOfSquares_{within}}{DegreesOfFreedom_{within}}}\]</span>
<br/></p>
<p>And this is a pretty complex formula if spelled out all the way. You can refer to Table 13.1 in <span class="citation">(Navarro &amp; Foxcroft, <a href="#ref-lsj" role="doc-biblioref">2019</a>, p. 334)</span> if you want to see how this works. In fact, Table 13.1 is in a standard ANOVA-table format, though we won’t go into that in this manual.</p>
<p>Naturally, you do not need to calculate the <em>F</em>-ratio by hand. jamovi will do it for you.</p>
<p><br/></p>
<div id="OnewayAnovaClinicalTrialData" class="section level3" number="8.1.1">
<h3><span class="header-section-number">8.1.1</span> Basic: Clinical Trial data</h3>
<p>The data set that Navarro and Foxcroft <span class="citation">(<a href="#ref-lsj" role="doc-biblioref">2019</a>)</span> use to illustrate the One-Way ANOVA is fictional. It is a hypothetical clinical trial in which which 18 patients with moderate to severe depression are recruited to participate in a trial in which half receive Cognitive Behavioral Therapy in contrast to half who do not. Each half then receives one of three drugs: <em>joyzepam</em>, <em>Anxifree</em> (a real antidepressant), and a placebo. Three participants are in each group, across both levels of therapy type. Their mood is measured at the beginning and then 3 months later on a 10-point scale from -5 to 5.</p>
<p>This lab manual simply presents the dataset and analysis in a more lab-like way.</p>
<p><br/></p>
<div id="OnewayAnovaClinicalTrialDataObtainingTheData" class="section level4" number="8.1.1.1">
<h4><span class="header-section-number">8.1.1.1</span> Obtaining the data</h4>
<p>To follow along yourself, you can open the in the module from <span class="citation">Navarro &amp; Foxcroft (<a href="#ref-lsj" role="doc-biblioref">2019</a>)</span>: <span class="math inline">\((\equiv)\)</span> &gt; <em>File</em> &gt; <em>Data Library</em> &gt; <em>learning statistics with jamovi</em> &gt; <em>Clinical Trial.omv</em>. We are only going to look at the effect of <em>drug</em> on <em>mood.gain</em> (the outcome variable).</p>
<p><br/></p>
</div>
<div id="OnewayAnovaClinicalTrialDataImplementing" class="section level4" number="8.1.1.2">
<h4><span class="header-section-number">8.1.1.2</span> Implementing the procedure</h4>
<p>Simply click the <em>Analyses</em> tab and select <em>ANOVA</em>. Choose the <em>ANOVA</em> option there too (skipping over the <em>One Way</em> option as that is more limited).</p>
<p>When the options window opens, slide <em>mood.gain</em> into the <em>Dependent Variables</em> box, and <em>drug</em> into the <em>Fixed Factors</em> box.</p>
<p>Under <em>Effect Size</em>, click either <span class="math inline">\(\eta^2\)</span> or <em>partial</em> <span class="math inline">\(\eta^2\)</span> (which are identical in a One-Way ANOVA).</p>
<p>See Figure <a href="ComparingSeveralMeans.html#fig:OneWayClinicalParametersMain">8.1</a> directly below for a depiction of these options.</p>
<div class="figure"><span id="fig:OneWayClinicalParametersMain"></span>
<img src="images/SeveralMeans/ANOVAClinicalParamatersMain.png" alt="Main parameter settings for the ANOVA procedure using the *Clinical Trial* data from @lsj." width="600px" />
<p class="caption">
Figure 8.1: Main parameter settings for the ANOVA procedure using the <em>Clinical Trial</em> data from <span class="citation">Navarro &amp; Foxcroft (<a href="#ref-lsj" role="doc-biblioref">2019</a>)</span>.
</p>
</div>
<p><br/></p>
<p>Next, click the arrow pointing to <em>Model</em> and make sure that <em>drug</em> is placed under <em>Model Terms</em> (and leave <em>Sum of squares</em> as <em>Type 3</em>. There is no built-in correction for heterogeneous variances in this procedure, but you can test the assumption using <em>Levene’s Test for Homogeneity of Variance</em>. This avails itself if you check the box <em>Homogeneity tests</em> under <em>Assumption Checks</em>. See Figure <a href="ComparingSeveralMeans.html#fig:ANOVAClinicalParamatersModelAndLevene">8.2</a> below for a depiction of these options.</p>
<div class="figure"><span id="fig:ANOVAClinicalParamatersModelAndLevene"></span>
<img src="images/SeveralMeans/ANOVAClinicalParamatersModelAndLevene.png" alt="Model settings and assumption checks for the ANOVA procedure using the *Clinical Trial* data from @lsj." width="600px" />
<p class="caption">
Figure 8.2: Model settings and assumption checks for the ANOVA procedure using the <em>Clinical Trial</em> data from <span class="citation">Navarro &amp; Foxcroft (<a href="#ref-lsj" role="doc-biblioref">2019</a>)</span>.
</p>
</div>
<p><br/></p>
<p>Under <em>Post-Hoc Tests</em>, make sure that <em>drug</em> is in the box on the right, and that the <em>Correction</em> is set to <em>Holm</em>. This is a more powerful way to conduct multiple post-hoc analyses than Bonferroni adjustments (see Navarro and Foxcroft <span class="citation">(<a href="#ref-lsj" role="doc-biblioref">2019</a>, sec. 13.5.4, pp. 343-344)</span> for a more thorough explanation). Scheffé and Tukey are also reasonable options. Ultimately however, all choices end up leading to the same conclusion in this case, which is often the case. See Figure <a href="ComparingSeveralMeans.html#fig:OneWayClinicalParametersPostHoc">8.3</a> below for how to select these options.</p>
<div class="figure"><span id="fig:OneWayClinicalParametersPostHoc"></span>
<img src="images/SeveralMeans/ANOVAClinicalParamatersPostHoc.png" alt="Multiple-comparison, post-hoc settings for the ANOVA procedure using the *Clinical Trial* data from @lsj." width="600px" />
<p class="caption">
Figure 8.3: Multiple-comparison, post-hoc settings for the ANOVA procedure using the <em>Clinical Trial</em> data from <span class="citation">Navarro &amp; Foxcroft (<a href="#ref-lsj" role="doc-biblioref">2019</a>)</span>.
</p>
</div>
<p><br/></p>
<p>Finally, under <em>Estimated Marginal Means</em>, make sure that the following are true:</p>
<ul>
<li><em>drug</em> makes it over to the box on the right under <em>Term 1</em><br />
</li>
<li>both boxes are checked under <em>Output</em> (<em>Marginal means plots</em> and <em>Marginal means tables</em>)<br />
</li>
<li><em>Equal cell weights</em> is checked (the default)<br />
</li>
<li><em>Error bars</em> (under <em>Plot</em>) is set to <em>Confidence interval</em><br />
</li>
<li>and for fun, check the box <em>Observed scores</em>.<a href="#fn74" class="footnote-ref" id="fnref74"><sup>74</sup></a></li>
</ul>
<p>These options are shown in Figure <a href="ComparingSeveralMeans.html#fig:ANOVAClinicalParamatersEMM">8.4</a> below.</p>
<div class="figure"><span id="fig:ANOVAClinicalParamatersEMM"></span>
<img src="images/SeveralMeans/ANOVAClinicalParamatersEMM.png" alt="Graphic settings for the ANOVA procedure using the *Clinical Trial* data from @lsj." width="600px" />
<p class="caption">
Figure 8.4: Graphic settings for the ANOVA procedure using the <em>Clinical Trial</em> data from <span class="citation">Navarro &amp; Foxcroft (<a href="#ref-lsj" role="doc-biblioref">2019</a>)</span>.
</p>
</div>
<p><br/></p>
<p>The results should appear as follows:</p>
<pre><code>## 
##  ANOVA
## 
##  ANOVA - mood.gain                                                                          
##  ────────────────────────────────────────────────────────────────────────────────────────── 
##                 Sum of Squares    df    Mean Square    F           p            η²p         
##  ────────────────────────────────────────────────────────────────────────────────────────── 
##    drug               3.453333     2     1.72666667    18.61078    0.0000865    0.7127623   
##    Residuals          1.391667    15     0.09277778                                         
##  ────────────────────────────────────────────────────────────────────────────────────────── 
## 
## 
##  ASSUMPTION CHECKS
## 
##  Homogeneity of Variances Test (Levene&#39;s) 
##  ──────────────────────────────────────── 
##    F           df1    df2    p           
##  ──────────────────────────────────────── 
##    1.449739      2     15    0.2656941   
##  ──────────────────────────────────────── 
## 
## 
##  POST HOC TESTS
## 
##  Post Hoc Comparisons - drug                                                                         
##  ─────────────────────────────────────────────────────────────────────────────────────────────────── 
##    drug             drug        Mean Difference    SE           df          t            p-holm      
##  ─────────────────────────────────────────────────────────────────────────────────────────────────── 
##    anxifree    -    joyzepam         -0.7666667    0.1758577    15.00000    -4.359586    0.0011211   
##                -    placebo           0.2666667    0.1758577    15.00000     1.516378    0.1502131   
##    joyzepam    -    placebo           1.0333333    0.1758577    15.00000     5.875963    0.0000914   
##  ─────────────────────────────────────────────────────────────────────────────────────────────────── 
## 
## 
##  ESTIMATED MARGINAL MEANS
## 
##  DRUG
## 
##  Estimated Marginal Means - drug                                  
##  ──────────────────────────────────────────────────────────────── 
##    drug        Mean         SE           Lower        Upper       
##  ──────────────────────────────────────────────────────────────── 
##    anxifree    0.7166667    0.1243502    0.4516206    0.9817128   
##    joyzepam    1.4833333    0.1243502    1.2182872    1.7483794   
##    placebo     0.4500000    0.1243502    0.1849539    0.7150461   
##  ────────────────────────────────────────────────────────────────</code></pre>
<p><img src="ElemStatsLabManual_files/figure-html/unnamed-chunk-138-1.svg" width="672" /></p>
<p><br/></p>
</div>
<div id="OnewayAnovaClinicalTrialDataInterpreting" class="section level4" number="8.1.1.3">
<h4><span class="header-section-number">8.1.1.3</span> Interpreting the output</h4>
<p>The first thing to notice is actually the second table down. For Levene’s test of Homogeneity of Variance, the null hypothesis is that the distributions of the variables is equal across groups (the assumption itself). Therefore, you want to fail to reject the null hypothesis, which is what happened here as <em>p</em> = .266. This also means that there is no problem interpreting the table above it, which is covered next.</p>
<p>The second thing to notice is the table at the top. This is known as an ANOVA table. It has a very specific structure. The key value is the <em>p</em>-value in the second-to-last column. It is below .05, so you can reject the null hypothesis that the three drugs have an equal effect on patients. How to report the <em>F</em>-test in APA format is covered below in section <a href="ComparingSeveralMeans.html#OnewayAnovaClinicalTrialDataReporting">8.1.1.4</a>.</p>
<p>However, another key value is in the last column. This is the effect size, <span class="math inline">\(\eta_p^2\)</span>. This statistic is also a bit redundant in the table since it is actually derived from column two. Well, when there is one predictor variable, it is equivalent to <span class="math inline">\(\eta^2\)</span> (<em>eta squared</em>), which is available from the table as the sum of squares between divided by the total sum of squares. The effect size here of .713 is quite large.</p>
<p><span class="math display">\[\eta^2 = \frac{SumOfSquares_{between}}{SumOfSquares_{total}}= \frac{SumOfSquares_{between}}{SumOfSquares_{between}+SumOfSquares_{within}}=\]</span>
<span class="math display">\[\frac{3.45}{3.45+1.39} = \frac{3.45}{4.84} = 0.713\]</span></p>
<p><br/></p>
<p>Naturally, that <em>F</em>-test is an omnibus test, and only tells us that there are some significant differences among the three means, but it doesn’t tell us which. Therefore, there are also some post-hoc tests that we called for, which are located in third table down. It appears that there is a significant difference between joyzepam and each of the other two drugs, but not between the other two drugs themselves. This is clear in the figure, where you can see that the confidence interval for joyzepam does not overlap with either of the other two drugs, but the confidence intervals of the other two drugs overlap with each other quite a bit.<a href="#fn75" class="footnote-ref" id="fnref75"><sup>75</sup></a></p>
<p>Also note that the <em>Estimated Marginal Means</em> may be slightly different than the means that you obtain from running <em>Exploration</em> &gt; <em>Descriptives</em> in jamovi. This topic is beyond the scope of this class as it has to do with how means are calculated multiple regression. Although these are legitimate estimates, you should report the means and standard deviations from the <em>Descriptives</em> procedure instead of the <em>Estimated Marginal Means</em> from the ANOVA output.</p>
<p><br/></p>
</div>
<div id="OnewayAnovaClinicalTrialDataReporting" class="section level4" number="8.1.1.4">
<h4><span class="header-section-number">8.1.1.4</span> Reporting the output</h4>
<p>As already shown in the case of chi-square, the <em>z</em>- and <em>t</em>-tests, and the correlation/regression chapter, APA requires a consistent pattern for reporting statistical output:</p>
<ol style="list-style-type: decimal">
<li>a letter (in italics) representing the test statistic used</li>
<li>parentheses that enclose the degrees of freedom</li>
<li>an equals sign</li>
<li>the obtained value of the test statistic</li>
<li>a comma</li>
<li>the letter <em>p</em> in italics</li>
<li>one of three symbols: =, &lt;, or &gt;</li>
<li>a <em>p</em>-value</li>
</ol>
<p><br/></p>
<p>There will be only two differences this time:</p>
<ul>
<li>The test letter is now <em>F</em> (not <em>t</em> or <span class="math inline">\(\chi^2\)</span>)<br />
</li>
<li>There are two degrees of freedom instead of one</li>
</ul>
<p>To report the <em>F</em>-test in APA format, you can get all the information you need from the second table in the output above (the ANOVA table). The test statistic is <em>F</em>. There are two degrees of freedom: one for the sum of squares between, and one for the sum of squares within. These are located in the third column under <em>df</em>. They are 2 an 15, respectively, in that order [i.e., (<span class="math inline">\(df_{between}\)</span>,<span class="math inline">\(df_{within}\)</span>)]. Next, we need the <em>F</em>-ratio itself, which is located in the fifth column under <em>F</em>. As noted above, the <em>p</em>-value is in the second-to-last column. We also report the effect size, which is in the last column. All together, the full report of the test statistic, in the order presented directly above, is as follows:</p>
<p><span class="math inline">\(F(2,15)=18.6,p&lt;.001, \eta_p^2=0.713\)</span></p>
<p><br/></p>
<p>We can now put together a partial <em>Results</em> section for this one analysis:</p>
<blockquote>
<p>The mood improvement over the course of three months differed significantly across the three groups of patients taking either <em>joyzepam</em>, <em>anxifree</em>, or a placebo, <span class="math inline">\(F(2,15)=18.6,p&lt;.001, \eta_p^2=0.713\)</span>. Post-hoc comparisons with Holm corrections revealed that there was a significant difference between <em>joyzepam</em> and both <em>anxifree</em> [<span class="math inline">\(t(15)=-4.36,p&lt;.001\)</span>] and the placebo [<span class="math inline">\(t(15)=5.88,p&lt;.001\)</span>]. However, there was no significant difference between <em>anxifree</em> and the placebo [<span class="math inline">\(t(15)=1.52,p=.15\)</span>]. These differences are also clear in Figure 1, where it is clear that the 95% confidence interval for <em>joyzepam</em> does not overlap with those of either of the other two conditions, whereas the confidence intervals for the latter two conditions overlap substantially. <em>joyzepam</em> is clearly resulting in a significantly greater mood gain than the other two conditions. Additionally, the effect size (<span class="math inline">\(\eta^2=0.713\)</span>) is quite large, suggesting that this difference between <em>joyzepam</em> and the other two conditions is quite substantial in magnitude.</p>
</blockquote>
<p><br/></p>
</div>
</div>
<div id="advanced" class="section level3" number="8.1.2">
<h3><span class="header-section-number">8.1.2</span> Advanced</h3>
<p><strong><em>Everything below Scheduled for Spring 2020</em></strong></p>
<p><br/></p>
</div>
</div>
<div id="repeated-measures-one-way-anova" class="section level2" number="8.2">
<h2><span class="header-section-number">8.2</span> Repeated-measures One-Way ANOVA</h2>
<p><br/></p>
</div>
<div id="outside-help-on-one-way-anova" class="section level2" number="8.3">
<h2><span class="header-section-number">8.3</span> Outside help on One-Way ANOVA</h2>
<p><br/></p>
<!-- ## Conclusion {#ConclusionOfOnewayAnova} -->
<!-- <br/> -->
</div>
<div id="PracticingOnewayAnova" class="section level2" number="8.4">
<h2><span class="header-section-number">8.4</span> Extra practice One-Way ANOVA</h2>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-lsj">
<p>Navarro, D. J., &amp; Foxcroft, D. R. (2019). Learning statistics with jamovi: A tutorial for psychology students and other beginners (Version 0.70). <a href="https://doi.org/10.24384/hgc3-7p15">https://doi.org/10.24384/hgc3-7p15</a></p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="73">
<li id="fn73"><p>Technically, you can also do this kind of test on a categorical variable with only two levels, something you would normally think to do an independent-samples <em>t</em>-test on. However, the results will be the same in this case, except that the ultimate obtained value for <em>F</em> (the ANOVA test) will be the equivalent of the obtained value for <em>t</em>, but squared. <span class="citation">(Navarro &amp; Foxcroft, <a href="#ref-lsj" role="doc-biblioref">2019</a>)</span> talk about this briefly in section 13.10.<a href="ComparingSeveralMeans.html#fnref73" class="footnote-back">↩︎</a></p></li>
<li id="fn74"><p>22 Oct 2019: Note however that you may get a strange message in German here: <em>unerwartetes Symbol 1:…</em>, which means “Unexpected symbol 1:….” This seems to be a bug in jamovi. If you get it, just uncheck the box; the error message goes away.<a href="ComparingSeveralMeans.html#fnref74" class="footnote-back">↩︎</a></p></li>
<li id="fn75"><p>Note that this is an approximate rule. Sometimes confidence intervals do overlap a little between variables that turn out to be significantly different.<a href="ComparingSeveralMeans.html#fnref75" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="CorrAndLinearReg.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="FactorialAnova.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "none",
"sharing": {
"github": true,
"facebook": false
}
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
